### ISSUE TITLE
Raising requests for getting API keys

### ISSUE THREAD

**Issue by vikramsunilpatil** [awslabs/aws-api-gateway-developer-portal#10]
How to take requests from third party developers for granting them access to gateway APIs instead of giving them an access key to try out the APIs. Any admin portal in AWS to approve these requests generated ?

**Comment by brettstack** [comment]
Perhaps you are looking for Marketplace Integration https://github.com/awslabs/aws-api-gateway-developer-portal#marketplace-saas-setup-instructions.

If you truly want to create API Keys manually from user requests:

The API Key is created in several areas of the code https://github.com/awslabs/aws-api-gateway-developer-portal/search?utf8=%E2%9C%93&q=createApiKey. You will need to remove these and add a way for users to request (email?) an API Key. You can then manually create API Keys from the API Gateway console https://backplane-console-beta-iad.amazon.com/apigateway/home?#/home or your preferred method.

This project is a reference implementation and intended for you to customize to your needs.
