### ISSUE TITLE
Support for API Gateway Extension (ANY Method)

### ISSUE THREAD

**Issue by a-tan** [awslabs/aws-api-gateway-developer-portal#101]
Originally requested by @bassmanitram in issue #35 

> Support for the AWS Extension ANY method (although I realize it's not particularly helpful as a Dev Portal "feature" to just shove out all known methods and let the dev crap-shoot around them :) ).

**Comment by MynockSpit** [comment]
Priority?

Possible ways of supporting this:
1. Convert 'ANY' to all of the others.
2. Patch swagger-ui to see 'ANY'.

Option 1 is much easier, but potentially confusing to Dev Portal owners. Option 2 is much harder and potentially confusing to Dev Portal customers.

**Comment by a-tan** [comment]
I like Option 1, its better aligned with APIGW's Console experience and we should avoid adding ANY into Swagger-ui since its not common outside of APIGW (afaik)
