### ISSUE TITLE
Incorrect API Set Up Instructions

### ISSUE THREAD

**Issue by scott-finlayson-kaptivo** [awslabs/aws-api-gateway-developer-portal#104]
Within the README.md file, it specifies that published APIs should be uploaded to the Artifacts S3 bucket in the format "apiId_stageName.json" (https://github.com/awslabs/aws-api-gateway-developer-portal). Upon following this with no luck and debugging, it appears the correct format is actually "apiId:stageName.json" (where a colon should be used rather than an underscore).

The issue can be seen within function "usagePlanToCatalogObject" where a apiStageKey (following format apiId:stageName) is compared against apiId_stageName. As the format is incorrect, this results in no match and therefor no published APIs.

Relates to https://github.com/awslabs/aws-api-gateway-developer-portal/issues/105

**Comment by scott-finlayson-kaptivo** [comment]
I believe you'll also need another change here: https://github.com/awslabs/aws-api-gateway-developer-portal/blob/master/lambdas/catalog-updater/index.js#L69
This is creating the apiStageKey which if you're using _ now, will never match if the apiStageKey is generated from the Swagger spec.

**Comment by Trial-In-Error** [comment]
Yep! The PR for fixing it is pending approvals and available here:

https://github.com/awslabs/aws-api-gateway-developer-portal/pull/106

Sorry for the delay on answering; github's had some availability issues today/yesterday.

**Comment by MynockSpit** [comment]
Closed by #106.

**Comment by Trial-In-Error** [comment]
Hey @scott-finlayson-kaptivo , if you ended up trying v2, is there any feedback you'd like to provide on setup or missing features?
