### ISSUE TITLE
CognitoIdentityPoolRoles creations fails

### ISSUE THREAD

**Issue by esc24** [awslabs/aws-api-gateway-developer-portal#11]
I cannot get the dev portal to deploy. When running `npm run setup` the cloudformation stack create/update step fails when attempting to create the `Custom::CognitoIdentityPoolRoles` resource. Digging into the logs I see:

```
"message": "User: arn:aws:sts::8XXXXXXXXX:assumed-role/DeveloperPortal-CognitoCustomResourceLambdaExecuti-KXXXXXXXXXX/DeveloperPortal-CognitoCustomResourceLambda-1XXXXXXXXXX is not authorized to perform: iam:PassRole on resource: arn:aws:iam::8XXXXXXXXXX:role/DeveloperPortal-CognitoAuthenticatedRole-6XXXXXXX",
"code": "AccessDeniedException"
```

Clearly it's a permissions error, but the IAM user I'm doing all this under has admin access. I've tried a couple of regions including us-east-1. I'm running node version 7.3.0, npm version 4.1.1 and awscli version is 1.11.33.

Any idea what might be causing this error?

**Comment by brettstack** [comment]
Thanks for bringing this to our attention. Please add "iam:PassRole" to CognitoCustomResourceLambdaExecutionRole. See https://github.com/awslabs/aws-api-gateway-developer-portal/commit/8842d6fbb8e4ba54061e7ba8e15c10618da90453.

**Comment by esc24** [comment]
Thanks for responding so quickly @brettstack . I'll have another go in the morning (it's late here in the UK) to verify the fix.

**Comment by brettstack** [comment]
Remember to first delete your stack, and you can run `npm run package-deploy` instead of `npm run setup`.
