### ISSUE TITLE
"Try it out" feature clears out values in textbox

### ISSUE THREAD

**Issue by a-tan** [awslabs/aws-api-gateway-developer-portal#122]
The "Try It Out" feature clears out values in the parameters textbox if they're required.
Repro steps are:
1) Login/Sign up
2) Go to an API, find one where there's a required parameter (eg: Get Pets with ID)
3) Click Try it Out
4) Type in a parameter
5) Click Execute
6) Parameter textbox clears and an error is thrown

**Comment by Trial-In-Error** [comment]
@of83 to get this fix for your developer portal instance, you can re-deploy to the same stack name with the same parameters, and make sure to include in the param overrides this parameter: `StaticAssetRebuildToken=anystringwhatsoever`. This will make sure that the (fixed) static assets get copied over. :)

**Comment by of83** [comment]
Thank you for the quick fix!
