### ISSUE TITLE
Sign-in and sign-out states in top-nav not refreshed

### ISSUE THREAD

**Issue by a-tan** [awslabs/aws-api-gateway-developer-portal#124]
The signed in/out states in the top nav bar are not refreshed to meet the current state. Repro:
1) Sign in
2) Sign in button is still visible in top nav
Alternatively
1) Sign out
2) Dashboard button is still visible in top nav

**Comment by MynockSpit** [comment]
Yeah, I noticed that... hmm.

**Comment by a-tan** [comment]
This was fixed in #146 which was part of the 2.2.1
