### ISSUE TITLE
Make creating the Route53 optional for custom domain integration

### ISSUE THREAD

**Issue by a-tan** [awslabs/aws-api-gateway-developer-portal#127]
My domain, and DNS are not hosted in Route53. It seems redundant for me to point my DNS at Route53 for the dev portal subdomain. Route53 creation should be optional (default not created)

**Comment by MynockSpit** [comment]
Maybe we ask for a Route53 *domain-name-something-something*, and if provided, associate it? (Or try to?) I don't know if that's even possible.

**Comment by Trial-In-Error** [comment]
I believe what Alan's getting at is:

`(exterior DNS provider w/nameservers) ---points at---> cloudfront domain (sj189248.cloudfront...) ---in front of---> S3 bucket`

The current flow is:
`(exterior registrar) ---points at---> Route53 nameservers ---points at---> cloudfront domain (sj189248.cloudfront...) ---in front of---> S3 bucket`

@a-tan is that correct?

**Comment by a-tan** [comment]
Yes, that's right. My setup is a little messier because foo.com still uses my registrar's name server but dev.foo.com uses route53's name server

**Comment by MynockSpit** [comment]
Oh, interesting. Is it possible to provide an option of 'Already registered a domain name with R53? Provide it and we'll hook it up for you.'

**Comment by Trial-In-Error** [comment]
We could, but I feel like we should wait for a customer to ask for it first. That's a large number of configurations ("create entirely managed" [R53+CF], "create partially managed" [existing R53+CF], "create minimally managed" [CF only]), and maintenance aside, will be hard to explain.
