### ISSUE TITLE
aws cloudformation deploy failure

### ISSUE THREAD

**Issue by ddimitrioglo** [awslabs/aws-api-gateway-developer-portal#13]
HI,

I receive the following error on `cloudformation deploy`:

> npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/ddmitrioglo/.nvm/versions/node/v4.7.2/bin/node" "/Users/ddmitrioglo/.nvm/versions/node/v4.7.2/bin/npm" "run" "deploy"
npm ERR! node v4.7.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! aws-serverless-dev-portal-example@1.0.0 deploy: `aws cloudformation deploy --template-file packaged-sam.yaml --stack-name $npm_package_config_cloudFormationStackName --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --parameter-overrides ArtifactsS3Bucket=$npm_package_config_artifactsS3Bucket DevPortalSiteS3Bucket=$npm_package_config_siteS3Bucket MarketplaceSubscriptionTopic=$npm_package_config_marketplaceSubscriptionTopic CognitoIdentityPoolName="$npm_package_config_identityPoolName" DevPortalCustomersTableName=$npm_package_config_customersTableName --region $npm_package_config_primaryAwsRegion`
npm ERR! Exit status 255

Should I update the repo or I can fix it somehow?

**Comment by ddimitrioglo** [comment]
I can not logs for CloudFormation, can you give me the hint?
I've also tried to remove all CloudFormation stacks, s3 buckets, DynamoDB tables and IAM roles, and create new once with long random names (to avoid duplicates), but it did not help...

**Comment by rpgreen** [comment]
Open the CloudFormation AWS console in a web browser. Navigate to the stack you're creating and you will see the log messages for that stack. From there you should be able to figure out what failed and rectify the problem. As I said earlier, it is likely a duplicate resource that needs to be manually removed.
