### ISSUE TITLE
UI fails to load, throws errors

### ISSUE THREAD

**Issue by anttikalliomaki** [awslabs/aws-api-gateway-developer-portal#14]
Hello,

Deploy script runs successfully, but I end up with a blank page with two errors in browser's console:

> ncaught TypeError: Cannot read property 'msie' of undefined
    at jquery.ba-bbq.min.js:18
    at jquery.ba-bbq.min.js:18

> reactProdInvariant.js:35Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=%20Check%20the%20render%20method%20of%20%60t%60. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r (reactProdInvariant.js:31)

The first error I was able to get around by modifying jquery.ba-bbq.min.js file as suggested here: http://stackoverflow.com/questions/23074644/jquery-bbq-generates-error-with-jquery-2

For the second, I'm still not sure what the root cause is. Is this something you've encountered?

I ran the deployment script on Windows with 'npm run win-setup'. No errors, a few warnings:

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.14 (node_modules\react-scripts\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.14 (node_modules\react-scripts\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

I'm using aws-cli version 1.11.44 and Node.js v6.9.1. 
Errors occur when running on AWS as well as in local deployment.

**Comment by anttikalliomaki** [comment]
Managed to close this by accident - reopening.

**Comment by rpgreen** [comment]
What browser are you using?

**Comment by mvillis** [comment]
running the dev-portal locally (Chrome Version 55.0.2883.95 (64-bit) ) here's the console output:

<img width="1121" alt="screen shot 2017-02-02 at 11 13 22 am" src="https://cloud.githubusercontent.com/assets/3509371/22533270/ba65b3a4-e938-11e6-85a5-1cee7d90a38c.png">

**Comment by brettstack** [comment]
Likely due to a minor version change. Taking a look.

**Comment by brettstack** [comment]
I missed the part where you're running this on Windows. I can verify setup works on Mac, and will check on Win box soon.

Also, you can ignore the jquery.ba-bbq.min.js error.

**Comment by brettstack** [comment]
Swapped to Node 6.9.1 as you are using and I can repro on Mac. Recommend downgrading to 5.6 if you want to get unblocked immediately (assuming this is easy for you, and you're using nvm or similar).

**Comment by mvillis** [comment]
I'm on a Mac and not having any luck. running node 7.5.

**Comment by brettstack** [comment]
The issue is with react-router; I guess it doesn't like newer versions of node. Updating react-router to latest version (react-router-dom), but since it's beta (we are currently on alpha) there are some API changes. Working on the changes now. You should be able to just pull down my branch (will have it up shortly) and replace the `dev-portal` directory.

**Comment by brettstack** [comment]
Easiest way to fix will be to apply these changes to your local copy https://github.com/awslabs/aws-api-gateway-developer-portal/commit/ced8ae075c7b9c879a817967d05389b9146c6eff. Then, run:

```bash
cd dev-portal
npm uninstall --save react-router
npm install --save react-router-dom@next
npm run start
```

Once you confirm it's working locally: `npm run package-deploy` from project root

**Comment by mvillis** [comment]
works perfectly. thank you!

**Comment by anttikalliomaki** [comment]
Yes, that did it. Thank you!
