### ISSUE TITLE
Can we have approval workflow for registration process?

### ISSUE THREAD

**Issue by anuroopkatta** [awslabs/aws-api-gateway-developer-portal#150]
When a user register can we have approval workflow to approve the users to have access to API’s and have the API key get created after the approval process is completed

**Comment by Trial-In-Error** [comment]
I'm going to close this; if you have any issues with the provided solution, please let us know!

**Comment by anuroopkatta** [comment]
Thank You. I will look in to creating the approval process using lambda.
