### ISSUE TITLE
User API key resets on hard page refresh

### ISSUE THREAD

**Issue by crawfobw** [awslabs/aws-api-gateway-developer-portal#154]
I'm noticing an issue where a signed in user's api key on 'My Dashboard' is reset on hard page refresh. This might be related to #124

**Comment by crawfobw** [comment]
There seem to be multiple issues with the state of the react app becoming screwed up. After closing out a tab with the developer portal open and opening a new one, I'm getting this error any time I try to access the dashboard page

`react-dom.production.min.js:3843 TypeError: Cannot read property 'swagger' of undefined`

**Comment by MynockSpit** [comment]
There's a known bug where attempting to sign in with an invalid user make the UI *think* it's signed in. It has no privileges and can't do anything, but it looks like it does. Sounds related. (Fix is here: https://github.com/awslabs/aws-api-gateway-developer-portal/pull/156)

Can you confirm that the user you're using is valid?

**Comment by crawfobw** [comment]
Yes the user is valid. Upon registration an API key is provisioned and inserted into the Dynamo table.

**Comment by MynockSpit** [comment]
Ah... I see at least half of the problem. We're not selecting an api if you have no "apiGateway" apis. I'll have a fix out for that shortly. 

Second problem is that for some reason your API Gateway api is being considered a "generic" api. Will have to look into that more.

Not yet sure why the API Key is being reset, though. Hmm.

**Comment by crawfobw** [comment]
I double checked the naming format for the swagger document and can confirm that it conforms to the `apiId_stageName.json` format. What is the criteria for determining if an api is generic?

**Comment by MynockSpit** [comment]
Hey! We just released [v2.2.4](https://github.com/awslabs/aws-api-gateway-developer-portal/releases/tag/v2.2.4) which should fix most of these issues. Please reopen if it didn’t!

**Comment by crawfobw** [comment]
Thanks! I'll give it a whirl tonight
