### ISSUE TITLE
Try-it-out button does not show until refresh/page reload

### ISSUE THREAD

**Issue by a-tan** [awslabs/aws-api-gateway-developer-portal#158]
After logging in, the try-it-out button does not show up until a refresh or the page is reloaded.
Repro:
1) Go to dev portal
2) Click on APIs
3) Login
4) No try it out button
5) Refresh
6) Try it out button appears

**Comment by MynockSpit** [comment]
Seems like this is fixed with [2.2.4](https://github.com/awslabs/aws-api-gateway-developer-portal/releases/tag/v2.2.4).
