### ISSUE TITLE
cannot access swagger UI after forcing api key in API Gateway

### ISSUE THREAD

**Issue by asad2k** [awslabs/aws-api-gateway-developer-portal#188]
Hi All,

We are working .net core web api project and all was going to plan but i decided to enable authentication using api-key...web api application is working fine when we pass api-key in the header but i can no longer access swagger ui...it says {"message":"Forbidden"}

any idea how to resolve this issue?

Many thanks

**Comment by MynockSpit** [comment]
Assuming this is an API gateway API, did you deploy, reexport, and recopy the swagger to the S3 bucket?

**Comment by MynockSpit** [comment]
Closing this. If this is still an issue, please feel free to re-open and add some more details! :)
