### ISSUE TITLE
Cannot show ApiDetails

### ISSUE THREAD

**Issue by ukgraphics** [awslabs/aws-api-gateway-developer-portal#19]
I get the following error and cannot show ApiDetails.
![appid](https://cloud.githubusercontent.com/assets/6788367/22721515/8750420c-edf4-11e6-8269-2979001912e1.png)

**Comment by reecefenwick** [comment]
I debugged it and did a JSON.stringify(this.props), which returned the following:

```javascript
{
  "path": "/apis/:apiId",
  "computedMatch": {
    "path": "/apis/:apiId",
    "url": "/apis/rqvt1w2wxg",
    "isExact": true,
    "params": {
      "apiId": "rqvt1w2wxg"
    }
  },
  "length": 36,
  "action": "POP",
  "location": {
    "pathname": "/apis/rqvt1w2wxg",
    "search": "",
    "hash": ""
  },
  "match": {
    "path": "/apis/:apiId",
    "url": "/apis/rqvt1w2wxg",
    "isExact": true,
    "params": {
      "apiId": "rqvt1w2wxg"
    }
  }
}
```

You should be able to see the path variable value a bit deeper in _props.match.params.apiId_ to be specific

I worked around it by changing the argument to getApi to this.props.match.params.apiId

```javascript
export default class ApiDetailsPage extends React.Component {
  constructor(props) {
    super(props)
    this.state = {}
    getApi(this.props.match.params.apiId)
    .then(api => {
      this.setState({
        api
      })
      loadSwagger(api.swagger)
    })
  }
```

I'm not familiar with react-router so I don't know if this is expected.

**Comment by ukgraphics** [comment]
Thanks you for letting me know. It works fine.

**Comment by brettstack** [comment]
Thanks for the report! Fixed.
