### ISSUE TITLE
Show Documentation/Description for API

### ISSUE THREAD

**Issue by a-tan** [awslabs/aws-api-gateway-developer-portal#192]
The Description field for the API is not shown but we do show the one for the paths themselves. We need to do this for the API itself so there's documentation there as well.

**Comment by idurant** [comment]
It seems like tags to not work either. All API resources show up under a section called `default`.

I don't see descriptions for and parameters, routes, or tags. Is this still a problem @a-tan? I'm looking to solve the problem otherwise I can't technically use the developer portal as a API guide..

**Comment by a-tan** [comment]
Hello @idurant this item here was only talking about the Description on the API -- everything else should have the proper documentation info displayed. Is this an API in API Gateway? If so, the issue might be that the documentation hasn't been deployed to the stage before you exported/published the API on to the Dev Portal. You can check by going to the API -> Stage -> Documentation History. You can publish the documentation by going to API -> Documentation -> Publish Documentation.

I have the latest version deployed here, you can sign up with any email to take a look: https://developer.exampleapigateway.com/

**Comment by idurant** [comment]
Okay gotcha, I didn't realize the documentation could be published separately from the API Resources. I did follow your steps but I still do not see any descriptions. This API was imported into the API Gateway via OpenApi 3.0 yaml. Things look good and work properly just no descriptions or resource separation. I'll keep digging

**Comment by a-tan** [comment]
Can you try this file and see if it works that it should help isolate whether the issue is with the version of the developer portal you have deployed or if its a configuration issue in API Gateway: https://github.com/a-tan/sampleOAS/blob/master/DPetStore-prod-oas30-apigateway.yaml

**Comment by idurant** [comment]
No luck using the Petstore example, looks like everything still shows under default with no descriptions. You are suggesting that my Dev Portal is out of date?

**Comment by a-tan** [comment]
If you use the same parameters, CFN will do an Update Stack which won't make you lose login credentials for devs/customers. You can check the stack in CloudFormation to get the parameters you used last time if you don't remember them. I would recommend going to the latest V2 version (minor version update) and then moving to V3 (major version update). Among several new features, in V3 we added an Admin interface so you don't need to export and drop it in S3 anymore.

You can do a trial run of these update steps by deploying another dev portal just for this purpose, just pass in DevPortalCustomersTableName="CustomersTableUpgradeTest" 

Relevant docs:
1) Minor version update - go to the latest v2 version - https://github.com/awslabs/aws-api-gateway-developer-portal#updating-to-a-new-version
1b) The default readme.md shows the command for V3, here's a link to a past version for deploying V2 - https://github.com/awslabs/aws-api-gateway-developer-portal/tree/c25949ca416b9b9cd0ffb629ce4a09855e13a06c
2) Major version update - go to the latest v3 version - https://github.com/awslabs/aws-api-gateway-developer-portal/wiki/Updating

**Comment by idurant** [comment]
Thanks for the information, I do have the admin panel where I can toggle and update the available APIs for consumers. Does that mean I have V3?

My info 
serverlessrepo:semanticVersion | 3.0.0
-- | --
**StackID** | serverlessrepo-api-gateway-dev-portal/4c33a690-6206-11e9-920c-0a163670bd44

**Comment by idurant** [comment]
I know our thread is getting log, let me know if I should log a new issue

**Comment by a-tan** [comment]
I thought you were on v2.x. I just tried on v3.0 with the PetStore YAML I sent you and it failed to import silently. My current hypothesis is that after you fixed the Documentation deployment it is failing to import silently for you too but you're not aware of that so it appears it imported successfully but you're actually looking at the old version still. 

Can you try this JSON one: https://github.com/a-tan/sampleOAS/blob/master/DPetStore-prod-oas30-apigateway.json

**Comment by idurant** [comment]
Just so we are clear, do you import through the Developer Portal UI or you import through API Gateway? I've been using the API gateway to import my yaml

**Comment by idurant** [comment]
Adding the .json file using the developer portal admin page worked properly. When I deleted it and added the .json file via API Gateway it did work this time. 

Is there a big difference between how the .yaml is executed versus .json, that would cause this to happen?

**Comment by a-tan** [comment]
There should be no difference, but it looks like the YAML version exported adds a "\" on long lines that the Dev Portal doesn't like. I opened #267 for tracking this.

**Comment by idurant** [comment]
okay, not looking forward to converting 500 lines of yaml to json 😞 . If I updated the documentation within the API Gateway shouldn't it reflect back to the Dev Portal, or, does the dev portal strictly use the markup as a definition to the API?

**Comment by a-tan** [comment]
The Dev Portal doesn't update automatically because it needs API Gateway to send an event on update that we can listen to (it doesn't do this today).

Are these APIs in API Gateway? If so there are a couple of options:
1) You can use the admin panel to pick and choose APIs, then you can skip the whole export and upload flow all together.
2) In API Gateway, you can just export to JSON in API Gateway instead of export to YAML. 

If not, you can use either a generic YAML to JSON converter, or use the Swagger Editor from Smartbear to change the format.

**Comment by idurant** [comment]
great, worked like a charm! Thank you for your efforts, I really appreciate all of the support.

**Comment by Trial-In-Error** [comment]
Looks like this is resolved; please open a new issue if you have any further problems. :)
