### ISSUE TITLE
Cannot re-write URL to dev portal

### ISSUE THREAD

**Issue by radiantone** [awslabs/aws-api-gateway-developer-portal#196]
Hi,
  We need to proxy the dev portal URL through our domain, but when we try to do this, the dev portal code seems to be taking the browser URL to obtain the S3 buckets and thus it does not work.

Code: NoSuchBucket
Message: The specified bucket does not exist
BucketName: www............com
RequestId: 46FDBBC81DD145E3
HostId: .....

Is there a way to set the bucket names in a configuration before deploying the portal so that it does not try to use the browser URL?

**Comment by a-tan** [comment]
Hello, if I am reading this correctly, it sounds like you would like to setup a custom domain for the developer portal. Have you taken a look at this? https://github.com/awslabs/aws-api-gateway-developer-portal#setup-a-custom-domain-for-your-developer-portal 
It will setup a CloudFront as a CDN and also handle the SSL termination for HTTPs, then you can simply point your own domain's DNS at the CloudFront distribution.

**Comment by Trial-In-Error** [comment]
Can you explain a bit more about your use case & the failure you're seeing?

It seems like you're using NGINX to route to the static asset bucket. Is the developer portal correctly fetching the initial HTML file (index.html), and the client-side javascript is fetching files from the wrong location? Or is it failing to fetch the index.html file? What does the failure look like? Can you provide a screenshot of the site, Chrome's network tab, or a HAR file of the failure?

**Comment by Trial-In-Error** [comment]
Closing due to lack of response. Please comment if you're still having the issue or would like to share the solution you've come to!
