### ISSUE TITLE
Show friendly names in description for API Keys created by dev portal

### ISSUE THREAD

**Issue by a-tan** [awslabs/aws-api-gateway-developer-portal#205]
API Keys created by the developer portal are guids. These guids are hard to connect back to the actual user the keys are vended for. In the description for the key, we should show the friendly name so they can be easily linked back to the user.

**Comment by Trial-In-Error** [comment]
The move to OAUTH / scope-based auth will actually change the key on this database from "cognito GUID" to "OAUTH email", so this issue will be resolvable then.

**Comment by Trial-In-Error** [comment]
Related to #234. Is the intent of this issue that the names of the API keys should be the user's User Pool username?
