### ISSUE TITLE
Add CORS headers to gateway responses for dev portal

### ISSUE THREAD

**Issue by Trial-In-Error** [awslabs/aws-api-gateway-developer-portal#227]
The dev portal doesn't return CORS headers on failures. Unauthorized requests, for instance, get thrown out by the browser for the lack of CORS headers. We should fix this by configuring gateway responses to include CORS headers in the swagger doc inlined in `template.yaml`

**Comment by idurant** [comment]
I enabled CORS through the s3 permissions and that fixed some of my problems but still certain methods return `TypeError: Failed to fetch` with `has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Adding CORS to certain routes has not fixed my problem

**Comment by a-tan** [comment]
@idurant CORS is enforced by the browser so it would be difficult to turn off generally. Are you describing the case where after you click "Try It Out" -> "Execute" the code section returns "TypeError: Failed to fetch" and then in the Inspect console of your browser it shows the message you pasted? This typically means that CORS was not enabled on the methods for the API published to the dev portal (the API that is shown on the dev portal). If the API uses proxy integration then the backend has to return the headers. 

Take a look at this doc on how to enable CORS: https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html

I created a negative test case on https://developer.exampleapigateway.com/, you can just sign up using any account, go to PetStore API, if you try to do a get on /nocors you should see the TypeError, on the other paths you will get a response.

**Comment by idurant** [comment]
@a-tan I thought I did have CORS enabled properly but there were some errors on the OPTIONS method created when you enable CORS. I decided to take another look after your response, I deleted the resource and added it back with a new method. That did seem to work, so I have something wrong with the swagger OpenAPI 3.0 yml file I made. I'll need to investigate but thank you for your efforts!

**Comment by Trial-In-Error** [comment]
Ok! Please let us know if you run into any other issues, but for the time being, I'm closing this issue.

**Comment by Trial-In-Error** [comment]
Hmm. This issue should remain open (we DO need to add CORS headers to the gateway responses for the dev portal), but the customer issue in the thread is resolved.

**Comment by duttonw** [comment]
Just converted a SAR dev portal from cloudfront domain dns to custom domain with acm cert and s3/cloudfront website can't get to api gateway with auth headers.

Access to XMLHttpRequest at 'https://randomdomain.execute-api.ap-southeast-2.amazonaws.com/prod/admin/catalog/visibility?start=undefined&end=undefined&sdkType=undefined' from origin 'https://customdomain' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

We can either fix the CORS issue or add to the script to add a custom domain to api-gateway so that it does not need to cross domain boundries. i.e api.${domain}/prod/admin/catalog.. when on ${domain}/admin

**Comment by duttonw** [comment]
Never mind about my issue, after getting an acm cert, i could not update the previous stack, I had to tear it all down and rebuild it again. no more cors issues on admin api gateway.

**Comment by Trial-In-Error** [comment]
Hey! I'm glad your setup is now working, but I'd like to understand what you did to end up with non-functional CORS. Can you help me re-trace your steps? It seems like it's something like:

1. Stand up a dev portal via SAR (with its included CloudFront distribution)
2. Create a custom domain name w/ ACM cert (in Route 53? Pointed at what origin?)
3. Receive CORS errors communicating with admin API on custom domain name (did the non-admin APIs work? getCatalog, etc?)

Also, how old was the SAR  dev portal? We fixed a few CORS issues with custom domains about 2-3 months ago. As it is, I don't think it should be possible to stand up a dev portal that doesn't have an Access-Control-Allow-Origin header on the admin api endpoints: see [this code here](https://github.com/awslabs/aws-api-gateway-developer-portal/blame/master/cloudformation/template.yaml#L459).

**Comment by duttonw** [comment]
I entered a custom domain, told it to create route53 but left acm blank. route53 was not created, i manually created the record and created the acm via dns cname (not email). I then updated the cloudformation template to have the acm cert arn. 

it then deleted the cloudfront distribution, updated some things and created cloudfront again and added a route53 zone.

cognito worked but no data from api gateway got through, so i updated the rebuild flags in the cloudformation template and this did not fix it.

then i pulled the stack down and create with same variables plus the acm cert. (re-added the acm cname route53 record so it does not fail next year).

from:
```
ArtifactsS3BucketName	${s3 bucket a}	-
CognitoDomainNameOrPrefix	agdptest	-
CognitoIdentityPoolName	DevPortalIdentityPool	-
CustomDomainName	${mysubdomain}	-
CustomDomainNameAcmCertArn	-	-
DevPortalAdminEmail	${my email}	-
DevPortalCustomersTableName	DevPortalCustomers	-
DevPortalFeedbackTableName	DevPortalFeedback	-
DevPortalSiteS3BucketName	${s3 bucket b}	-
DevelopmentMode	false	-
MarketplaceSubscriptionTopicProductCode	DevPortalMarketplaceSubscriptionTopic	-
StaticAssetRebuildMode	-	-
StaticAssetRebuildToken	defaultRebuildToken	-
UseRoute53Nameservers	true
```

to
```
ArtifactsS3BucketName	${s3 bucket a}	-
CognitoDomainNameOrPrefix	agdptest	-
CognitoIdentityPoolName	DevPortalIdentityPool	-
CustomDomainName	${mysubdomain}	-
CustomDomainNameAcmCertArn	arn:aws:acm:us-east-1:${account}/${cert}	-
DevPortalAdminEmail	${my email}	-
DevPortalCustomersTableName	DevPortalCustomers	-
DevPortalFeedbackTableName	DevPortalFeedback	-
DevPortalSiteS3BucketName	${s3 bucket b}	-
DevelopmentMode	false	-
MarketplaceSubscriptionTopicProductCode	DevPortalMarketplaceSubscriptionTopic	-
StaticAssetRebuildMode	-	-
StaticAssetRebuildToken	defaultRebuildToken	-
UseRoute53Nameservers	true
```

It would be nice if the api gateway was placed on the same domain. e.g. website at domain and api. for api  gateway. or more advanced roll it together with cloudfront config rules for /api to point to api gateway domain.

**Comment by bugske** [comment]
Hi,

I also face a CORS error while trying to change the visibility of an API... Deployed the application using SAM & the last version of the scripts without any custom domain:

`16:31:12.976 POST https://7czk4e4o7h.execute-api.eu-west-1.amazonaws.com/prod/admin/catalog/visibility 504
16:31:12.976 7czk4e4o7h.execute-api.eu-west-1.amazonaws.com/prod/admin/catalog/visibility:1 POST https://7czk4e4o7h.execute-api.eu-west-1.amazonaws.com/prod/admin/catalog/visibility 504
16:31:12.976 admin:1 Access to XMLHttpRequest at 'https://7czk4e4o7h.execute-api.eu-west-1.amazonaws.com/prod/admin/catalog/visibility' from origin 'https://d16sfolymmtza4.cloudfront.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Any easy/quick fix for this?

**Comment by dniel** [comment]
Hi, seem to have the same problem, deployed with SAM without custom domain and it worked and displayed my API's. Updated the deployment from Cloud Formation with custom domain and certificate, updated the stack and now I get the same problem with CORS errors in the console.

**Comment by veeramani29** [comment]
Hi ,

I am facing the error **No 'Access-Control-Allow-Origin'**  kindly let me know how to resolve.

I have tried with custom domain and without custom domain
1.https://apiportals.veteranequipments.com/ (Custom)
2.https://d2q535ty0845oe.cloudfront.net (Without custom)
**Error:**
Access to XMLHttpRequest at 'https://ubn3jdi87e.execute-api.us-east-1.amazonaws.com/prod/catalog?start=undefined&end=undefined&sdkType=undefined' from origin 'https://apiportals.veteranequipments.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested  [#resource.](url)
**Parameters:**
AccountRegistrationMode	open	
ArtifactsS3BucketName	claysolapiartifacts	
CognitoDomainNameOrPrefix	agdptest	
CognitoIdentityPoolName	DevPortalIdentityPool	
CustomDomainName	yy.xx.com	
CustomDomainNameAcmCertArn	arn:aws:acm:useast1:{ur}:certificate/{ur}	
DevPortalAdminEmail	veeramanishines@gmail.com	
DevPortalCustomersTableName	DevPortalCustomers	
DevPortalFeedbackTableName	DevPortalFeedback	
DevPortalPreLoginAccountsTableName	DevPortalPreLoginAccounts	
DevPortalSiteS3BucketName	claysolapistaticcontents	
DevelopmentMode	false	
LocalDevelopmentMode	false	
MarketplaceSubscriptionTopicProductCode	DevPortalMarketplaceSubscriptionTopic	
StaticAssetRebuildMode		
StaticAssetRebuildToken	defaultRebuildToken	
UseRoute53Nameservers	true

**Comment by veeramani29** [comment]
> Hi,
> 
> I also face a CORS error while trying to change the visibility of an API... Deployed the application using SAM & the last version of the scripts without any custom domain:
> 
> `16:31:12.976 POST https://XXXXXXX.execute-api.eu-west-1.amazonaws.com/prod/admin/catalog/visibility 504 16:31:12.976 XXXXXXX.execute-api.eu-west-1.amazonaws.com/prod/admin/catalog/visibility:1 POST https://7czk4e4o7h.execute-api.eu-west-1.amazonaws.com/prod/admin/catalog/visibility 504 16:31:12.976 admin:1 Access to XMLHttpRequest at 'https://7czk4e4o7h.execute-api.eu-west-1.amazonaws.com/prod/admin/catalog/visibility' from origin 'https://d16sfolymmtza4.cloudfront.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
> 
> Any easy/quick fix for this?

Hey ,

The issues is here 
Under Api gateway console ->Method Execution ->Settings 
Authorization AWS_IAM  to NONE its working fine
Do force refresh or clear cloudfront cache

**Comment by veeramani29** [comment]
> Hi ,
> 
> I am facing the error **No 'Access-Control-Allow-Origin'** kindly let me know how to resolve.
> 
> I have tried with custom domain and without custom domain
> 1.https://apiportals.veteranequipments.com/ (Custom)
> 2.https://d2q535ty0845oe.cloudfront.net (Without custom)
> **Error:**
> Access to XMLHttpRequest at 'https://ubn3jdi87e.execute-api.us-east-1.amazonaws.com/prod/catalog?start=undefined&end=undefined&sdkType=undefined' from origin 'https://apiportals.veteranequipments.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested [#resource.](url)
> **Parameters:**
> AccountRegistrationMode open
> ArtifactsS3BucketName claysolapiartifacts
> CognitoDomainNameOrPrefix agdptest
> CognitoIdentityPoolName DevPortalIdentityPool
> CustomDomainName yy.xx.com
> CustomDomainNameAcmCertArn arn:aws:acm:useast1:{ur}:certificate/{ur}
> DevPortalAdminEmail [xx@gmail.com](mailto:xx@gmail.com)
> DevPortalCustomersTableName DevPortalCustomers
> DevPortalFeedbackTableName DevPortalFeedback
> DevPortalPreLoginAccountsTableName DevPortalPreLoginAccounts
> DevPortalSiteS3BucketName claysolapistaticcontents
> DevelopmentMode false
> LocalDevelopmentMode false
> MarketplaceSubscriptionTopicProductCode DevPortalMarketplaceSubscriptionTopic
> StaticAssetRebuildMode
> StaticAssetRebuildToken defaultRebuildToken
> UseRoute53Nameservers true

Hey ,

The issues is here 
Under Api gateway console ->Method Execution ->Settings 
Authorization AWS_IAM  to NONE its working fine
Do force refresh or clear cloudfront cache

**Comment by veeramani29** [comment]
> I enabled CORS through the s3 permissions and that fixed some of my problems but still certain methods return `TypeError: Failed to fetch` with `has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
> 
> Adding CORS to certain routes has not fixed my problem, is it possible to disallow the UI from expecting CORS? I also added 'Access-Control-Allow-Origin' head to cloudfront. Still getting a 403 😞

Hey ,

The issues is here 
Under Api gateway console ->Method Execution ->Settings 
Authorization AWS_IAM  to NONE its working fine
Do force refresh or clear cloudfront cache

**Comment by amazon-meaisiah** [comment]
Should be fixed in v4 with the introduction of an edge lambda that adds those headers. Closing as there hasn't been a response in a while.
