### ISSUE TITLE
Publish APIs in from different accounts on one dev portal

### ISSUE THREAD

**Issue by a-tan** [awslabs/aws-api-gateway-developer-portal#232]
Admin can publish APIs hosted in API Gateway from different accounts on to one Dev Portal. These "out of account" APIs have the same support and capabilities as a normal "in the account" API. For example, customers of the Dev Portal can get an API key, associate it with a usage plan, and monitor usage.

**Comment by Trial-In-Error** [comment]
Dupe of #231. Closing.
