### ISSUE TITLE
Overview of users <-> API keys

### ISSUE THREAD

**Issue by Siflei** [awslabs/aws-api-gateway-developer-portal#234]
As an admin of the developer portal I want to see (and export) a list of all registered users and their API keys.
(Could I do that programmaticaly in a lambda by myself?)

**Comment by a-tan** [comment]
Today on each API Key created through the Dev Portal, the name and description are the IDs for Cognito Identity Pool Identities. The usernames/email addresses are stored in Cognito User Pool. There's no easy way to create the relationship post-auth. Here's a related StackOverflow post if you would like to do that during auth: https://stackoverflow.com/questions/37963906/how-to-get-user-attributes-username-email-etc-using-cognito-identity-id 

That said, we will add this capability as a result of us working on #205 which should be available in the next update.

**Comment by Siflei** [comment]
Hi a-tan, thanks for your answer!
How dows the Dev. Portal show the API key on the dashboard then? There must be a connection between the logged in user and the key, somewehere.

Can you roughly say when the update you mentioned will be available?

Simon

**Comment by a-tan** [comment]
Hi Simon,

Yeah, let me give more details here -- at the high level, the sign in roughly works like this:
1) User logins in through Cognito User Pool. The Cognito User Pool is associated with a Cognito Identity Pool.
2) The user's identity gets mapped to a Cognito Identity Pool ID
3) The Developer Portal gets the Cognito Identity Pool ID and gives it an API Key if it doesn't already have one assigned.

For the purposes of the Dev Portal we're able to connect an API Key with a logged in user (Cognito Identity Pool) as per step 3. 

However as an admin of the dev portal, I think you actually want the identity from step 1 which is not easily retrievable today unless you have the identity object itself.

So to enable this scenario, we're going to take an additional step during step 3 to record the identity from step 1. We're aiming for before end of the month.

Thanks,
Alan

**Comment by a-tan** [comment]
Hello, the newest version has this addition now.
For an API Key you will see it in this format: 

Name:
us-east-1:794e99a4-f28f-44b4-98c1-1812dd611180/51f8c60a-d1b7-41a1-b1de-cebd99db11f2
Description:
Dev Portal API Key for Identity Pool user us-east-1:794e99a4-f28f-44b4-98c1-1812dd611180 / User Pool user 51f8c60a-d1b7-41a1-b1de-cebd99db11f2

Using the User Pool guid (second part after /), you can join it with the list of users in user pool to get their friendly name.

**Comment by Trial-In-Error** [comment]
Closing. Please re-open if you have any questions or run into any problems with v3.0.0, @Siflei.
