### ISSUE TITLE
Query strings are not getting appended to the request URL for GET method API's

### ISSUE THREAD

**Issue by tecmaverick** [awslabs/aws-api-gateway-developer-portal#256]
Hello,

Query strings are not getting appended to the request URL for GET method API's within AWS Developer Portal. After entering values for query strings, such are not being appended to the request URL. This can also be seen within the Curl that AWS Developer Portal produces once the Execute button is clicked.

**Comment by Trial-In-Error** [comment]
What version of the developer portal are you using? This is a known bug with SwaggerUI that we've worked around already. I just tested against a v3.0.0 developer portal, and it appears to be working.

**Comment by a-tan** [comment]
We can't repro this, closing for now. Feel free to reopen with more details.
