### ISSUE TITLE
How to disable Marketplace feature

### ISSUE THREAD

**Issue by idurant** [awslabs/aws-api-gateway-developer-portal#259]
I want to use this Cloudformation template for customers to view/call the api through a UI but I do not want my API added to the Marketplace. Do I simply remove `MarketplaceSubscriptionTopicProductCode` from my cloudformation template?

Thank in advance for the help

**Comment by idurant** [comment]
Closing this issue, after finding the official AWS guide, I see that adding the API to the marketplace is a feature of the api gateway publishing, and not this template itself. ✌️

**Comment by Trial-In-Error** [comment]
Glad the docs helped!
