### ISSUE TITLE
Overriding custom content does not work

### ISSUE THREAD

**Issue by aroques** [awslabs/aws-api-gateway-developer-portal#263]
Followed the directions on the wiki to add custom content: https://github.com/awslabs/aws-api-gateway-developer-portal/wiki/Customization.

Have custom content in dev-portal/public/custom-content/ and run sam package, then sam deploy with StaticAssetRebuildToken="[_CurrentTimeStamp_]" and StaticAssetRebuildMode="overwrite_content", and no custom content is rendered in my dev portal website. Nor is it  uploaded to my static assets bucket. Is this a bug or am I performing some step incorrectly?

**Comment by aroques** [comment]
StaticAssetRebuildMode needs to be "overwrite-content" not "overwrite_content". The documentation [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-developer-portal.html?shortFooter=true#apigateway-developer-portal-update) and customization page on the [wiki](https://github.com/awslabs/aws-api-gateway-developer-portal/wiki/Customization) should be updated.

**Comment by Trial-In-Error** [comment]
Ah! I've updated the wiki and CFN template, and will see about updating the docs. Thanks for the bug report.
