### ISSUE TITLE
update ui to work on mobile

### ISSUE THREAD

**Issue by duttonw** [awslabs/aws-api-gateway-developer-portal#269]
When looking at a dev portal on a phone, the sidebar (where the api's go) take up most of the space. Is it possible to add something that confluence has at the bottom to shrink or unshrink the side bar or collapse it into a triple line thing that lets you pick an api and then hides again or tabs. https://uxplanet.org/alternatives-of-hamburger-menu-a8b0459bf994

**Comment by gbroques** [comment]
I accidentally created a duplicate in issue #299.

I may find some time to improve the responsiveness of the navigation menu and add a responsive `<meta>` tag.
