### ISSUE TITLE
Overriding custom content does not work

### ISSUE THREAD

**Issue by blomm** [awslabs/aws-api-gateway-developer-portal#315]
I have these two scripts in my package.json, package and deploy
in deploy I specify StaticAssetRebuildToken and StaticAssetRebuildMode
they worked to deploy the developer portal, but now that I want to update some of the custom-content it is not working... when i run the deploy, the bucket items get updated but always with the same home-image.png, not the new one that I've placed in my custom-content folder. Help please!

"package": "sam package --template-file ./cloudformation/template.yaml --output-template-file ./cloudformation/packaged.yaml --s3-bucket lambda-artifacts",

"deploy": "sam deploy --template-file ./cloudformation/packaged.yaml --stack-name 'dev-portal' --s3-bucket lambda-artifacts --capabilities CAPABILITY_NAMED_IAM --parameter-overrides StaticAssetRebuildToken={$(date \"+%s\")} StaticAssetRebuildMode='overwrite-content' DevPortalSiteS3BucketName='dev-portal-static-assets' ArtifactsS3BucketName='dev-portal-artifacts' CognitoDomainNameOrPrefix='my-custom-portal' CustomDomainName='api-docs.some-site.com' CustomDomainNameAcmCertArn='arn:aws:acm:us-east-1:123243:certificate/abc-123' UseRoute53Nameservers='true'",

**Comment by HimanshuShuklaCoder** [comment]
what was the issue bloom, I am trying it but the assets are not updating.

**Comment by KevinNha** [comment]
Trying to change my custom content but it won't be updapted. 
Any updates?

**Comment by KevinNha** [comment]
> what was the issue bloom, I am trying it but the assets are not updating.

Did you find a fix for this?
