### ISSUE TITLE
Update Lambda runtime to Node10

### ISSUE THREAD

**Issue by whitekb** [awslabs/aws-api-gateway-developer-portal#319]
Currently Node8.x is used as runtime for the Lambda functions.

Node8.x will reach it's EOL at the end of 2019.
As of Janurary 6th, 2020 you will no longer be able to create Lambda functions with Node8.x runtime.
As of February 3, 2020 you will not be able to update existing Node8 functions.

(information taken from AWS notification mails)

**Comment by gres147679** [comment]
Seems fixed by https://github.com/awslabs/aws-api-gateway-developer-portal/commit/7dfea1207636c72df09ca864855c4d809587e6ab

[Deploying this via SAR still fails](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-developer-portal.html), however
