### ISSUE TITLE
APIs are duplicated in API list after becoming subscribable

### ISSUE THREAD

**Issue by dylanbudgen** [awslabs/aws-api-gateway-developer-portal#325]
If a non-subscribable API is displayed in the portal, and then converted to a subscribable API, it will become visible in both the subscribable and not subscribable section of the APIs list. 

The API no longer shows as not subscribable in the admin panel so it is impossible to remove from the Not Subscribable view without manual deletion from the S3 bucket.

**Comment by stormlrd** [comment]
a workaround is to go into the admin portal and turn off and on the displaying of the API.

**Comment by amazon-meaisiah** [comment]
Should be resolved in v4.0.0, and the above workaround is the proper way to address it.
