### ISSUE TITLE
Using Linux distributions of node can cause the react build to fail

### ISSUE THREAD

**Issue by bassmanitram** [awslabs/aws-api-gateway-developer-portal#33]
[This issue](https://github.com/facebookincubator/create-react-app/issues/984) isn't specific to this project, but it does cause the project to fail:

```
> dev-portal@0.1.0 build /home/jbartle9/Development/AWS/APIGateway/AIA/aws-api-gateway-developer-portal/dev-portal
> react-scripts build

Creating an optimized production build...
Failed to compile.

static/js/main.91fca694.js from UglifyJs
Unexpected character '`' [/usr/lib/nodejs/events.js:260,0]
```

[This appears to explain the root cause issue](https://github.com/facebookincubator/create-react-app/pull/1194) (node distribution source making it into NODE_PATH). I am far from proficient in npm/node, let alone react, so I really don't know what needs changing to this project to alleviate this problem for us Linux users.

**Comment by bassmanitram** [comment]
Workaround (at least for Ubuntu 16.04 and Node  v6.10 installed from standard repos):

```
echo $NODE_PATH
NODE_PATH=<previous response with /usr/lib/nodejs: removed> npm run setup
```

**Comment by brettstack** [comment]
Thanks for reporting and documenting. I'm going to close this issue since it isn't related to us, but hopefully it will be useful for others who encounter the same issue and come across this via search or other. Thanks!
