### ISSUE TITLE
When the page loads at end of process it is empty

### ISSUE THREAD

**Issue by bassmanitram** [awslabs/aws-api-gateway-developer-portal#34]
Process [from fresh clone with no changes] completes successfully and opens a tab in Chrome (or FF) - which is empty.

[Console log from chrome attached](https://github.com/awslabs/aws-api-gateway-developer-portal/files/820994/mjb-api-portal.s3-website-eu-west-1.amazonaws.com-1488800602514.txt)

**Comment by scotty-p** [comment]
I can recreate this issue

**Comment by brettstack** [comment]
I'll spin up a fresh instance and see if I can repro (and fix). This is the error that's causing the problem:

Link.js:72Uncaught TypeError: Cannot read property 'createHref' of undefined

**Comment by brettstack** [comment]
Update `./dev-portal/package.json` and change `"react-router-dom": "^4.0.0-beta.4"` to `"react-router-dom": "4.0.0-beta.7"`.

From `./dev-portal` run:

```
rm -rf node_modules
npm install
npm run start
```

After the final command kicks in, visit http://localhost:3000/ and verify it runs locally. Then, run `npm run upload-site` to deploy.

**Comment by brettstack** [comment]
Root cause: react-router-dom is in beta; API is in flux. Since we allow minor version changes (^), the API changes in newer versions of react-router-dom beta broke the app.

Solution: Remove ^ from react-router dom. In fact, to be safe, we will be removing it from all packages.

**Comment by bassmanitram** [comment]
Excellent - thanks - now onto a real API :)

**Comment by jose-rafael-marcano** [comment]
It didn't work for me

I had to add "react-router": "4.0.0-beta.7" in addition to current dependencies, but now I am not getting the sign in or register option. It is displaying Case Studies, APIs and Getting Started, but not register/login options. I am wondering if this is related to cache. Please @brettstack help out.

![image](https://cloud.githubusercontent.com/assets/23706030/23781935/7452bd1a-0505-11e7-823b-7f071151f1de.png)

**Comment by jose-rafael-marcano** [comment]
I found the issue, it was a problem with my package.json. I had to add  "react-router": "4.0.0-beta.7", in addition to "react-router-dom": "4.0.0-beta.7".
Thanks

**Comment by jessetarot** [comment]
@jose-rafael-marcano your solution of adding `"react-router": "4.0.0-beta.7"` to package.json
worked for me too. Thanks for posting.
