### ISSUE TITLE
Not displaying the "OPTION" method of an API in the portal

### ISSUE THREAD

**Issue by seinecle** [awslabs/aws-api-gateway-developer-portal#349]
When CORS is enabled on API endpoints, it creates an OPTION method for the resources. This OPTION method appears in the dev portal, even if there is no use for the end user of the API.

Could it be possible to disable the display of OPTION methods in the portal?

**Comment by rosiech** [comment]
Go to S3 and find the bucket that the dev portal is in.
In the custom content folder download the styles.css file and edit it to include:

.opblock-options {
    display: none;
}

and upload it again.

**Comment by seinecle** [comment]
Thx!
