### ISSUE TITLE
A couple of feature requests

### ISSUE THREAD

**Issue by bassmanitram** [awslabs/aws-api-gateway-developer-portal#35]
* From an API ID and Plan ID, automatically download the swagger for the included APIs from the included stages.
* Support for the AWS Extension ANY method (although I realize it's not particularly helpful as a Dev Portal "feature" to just shove out all known methods and let the dev crap-shoot around them :) ).

**Comment by pjaleeuwen** [comment]
* Support for automated deployment.

**Comment by a-tan** [comment]
@pjaleeuwen automated deployments are possible now with the recent updates to make the Developer Portal deployable using SAM, and also the update to generate the catalog from S3 bucket.

@bassmanitram i've split out your requests so they're individually trackable
