### ISSUE TITLE
Main page empty

### ISSUE THREAD

**Issue by jose-rafael-marcano** [awslabs/aws-api-gateway-developer-portal#36]
I did run win-setup; cloudformation executed correctly and has errors. Index page displayed, but there is no information, it is displaying only the title and the icon. 

-I have awscli-1.11.57
-node --version 
v6.9.1

Am I missing one step because i am using windows? 

Did someone has an issue with empty page not displaying login option or documentation option?
I have same issue locally or using s3 web hosting.

**Comment by jose-rafael-marcano** [comment]
Below my index.html deployed to AWS account.
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <link rel="shortcut icon" href="/favicon.ico">
      <script type="text/javascript" src="/apigateway-js-sdk/lib/axios/dist/axios.standalone.js"></script><script type="text/javascript" src="/apigateway-js-sdk/lib/CryptoJS/rollups/hmac-sha256.js"></script><script type="text/javascript" src="/apigateway-js-sdk/lib/CryptoJS/rollups/sha256.js"></script><script type="text/javascript" src="/apigateway-js-sdk/lib/CryptoJS/components/hmac.js"></script><script type="text/javascript" src="/apigateway-js-sdk/lib/CryptoJS/components/enc-base64.js"></script><script type="text/javascript" src="/apigateway-js-sdk/lib/url-template/url-template.js"></script><script type="text/javascript" src="/apigateway-js-sdk/lib/apiGatewayCore/sigV4Client.js"></script><script type="text/javascript" src="/apigateway-js-sdk/lib/apiGatewayCore/apiGatewayClient.js"></script><script type="text/javascript" src="/apigateway-js-sdk/lib/apiGatewayCore/simpleHttpClient.js"></script><script type="text/javascript" src="/apigateway-js-sdk/lib/apiGatewayCore/utils.js"></script><script type="text/javascript" src="/apigateway-js-sdk/apigClient.js"></script><script src="/jquery-2.1.4.min.js"></script>
      <link href="/swagger-ui/dist/css/typography.css" media="screen" rel="stylesheet"/>
      <link href="/swagger-ui/dist/css/reset.css" media="screen" rel="stylesheet"/>
      <link href="/swagger-ui/dist/css/screen.css" media="screen" rel="stylesheet"/>
      <link href="/swagger-ui/dist/css/reset.css" media="print" rel="stylesheet"/>
      <link href="/swagger-ui/dist/css/print.css" media="print" rel="stylesheet"/>
      <script src="/swagger-ui/dist/lib/object-assign-pollyfill.js" type="text/javascript"></script><script src="/swagger-ui/dist/lib/jquery.slideto.min.js" type="text/javascript"></script><script src="/swagger-ui/dist/lib/jquery.wiggle.min.js" type="text/javascript"></script><script src="/swagger-ui/dist/lib/jquery.ba-bbq.min.js" type="text/javascript"></script><script src="/swagger-ui/dist/lib/handlebars-4.0.5.js" type="text/javascript"></script><script src="/swagger-ui/dist/lib/lodash.min.js" type="text/javascript"></script><script src="/swagger-ui/dist/lib/backbone-min.js" type="text/javascript"></script><script src="/swagger-ui/dist/swagger-ui.js" type="text/javascript"></script><script src="/swagger-ui/dist/lib/highlight.9.1.0.pack.js" type="text/javascript"></script><script src="/swagger-ui/dist/lib/highlight.9.1.0.pack_extended.js" type="text/javascript"></script><script src="/swagger-ui/dist/lib/jsoneditor.min.js" type="text/javascript"></script><script src="/swagger-ui/dist/lib/marked.js" type="text/javascript"></script><script src="/swagger-ui/dist/lib/swagger-oauth.js" type="text/javascript"></script>
      <title>Developer Portal</title>
      <link href="/static/css/main.27c1a0ac.css" rel="stylesheet">
   </head>
   <body>
      <div id="root"></div>
      <script type="text/javascript" src="/static/js/main.0cd1d293.js"></script>
   </body>
</html>

**Comment by jose-rafael-marcano** [comment]
in debug option of browser i see this:
SCRIPT5007: Unable to get property 'msie' of undefined or null reference 
jquery.ba-bbq.min.js, line 18 character 115
SCRIPT5007: Unable to get property 'createHref' of undefined or null reference 
main.0cd1d293.js, line 14 character 1250

**Comment by jose-rafael-marcano** [comment]
Uncaught TypeError: Cannot read property 'msie' of undefined
    at jquery.ba-bbq.min.js:18
    at jquery.ba-bbq.min.js:18
main.0cd1d293.js:14 Uncaught TypeError: Cannot read property 'createHref' of undefined
    at t.render (main.0cd1d293.js:14)
    at l._renderValidatedComponentWithoutOwnerOrContext (main.0cd1d293.js:29)
    at l._renderValidatedComponent (main.0cd1d293.js:29)
    at l.performInitialMount (main.0cd1d293.js:28)
    at l.mountComponent (main.0cd1d293.js:28)
    at Object.mountComponent (main.0cd1d293.js:4)
    at y.mountChildren (main.0cd1d293.js:29)
    at y._createInitialChildren (main.0cd1d293.js:29)
    at y.mountComponent (main.0cd1d293.js:29)
    at Object.mountComponent (main.0cd1d293.js:4)
DevTools failed to parse SourceMap: http://my-josem-developer-portal-app-test-developer-portal-app.s3-website-us-west-2.amazonaws.com/apigateway-js-sdk/lib/axios/dist/axios.map

**Comment by brettstack** [comment]
Please see #34

**Comment by jose-rafael-marcano** [comment]
Thanks brettstack, i will try that solution, it looks cleaner, because i modified 2 js files, one in swagger and the other one in node_modules\react-router-dom\Link.js

So basically i modified this:

1-In jquery library swagger-ui\dist\lib\jquery.ba-bbq.min.js, I changed this code:

f=$.browser,g=document.documentMode,h=f.msie&&(g===b||g<8)

replace by  f=$.browser,g=document.documentMode,h=false

So it won’t work with internet explorer version less than 8


2- problemin node_modules\react-router-dom\Link.js

var href = this.context.router.createHref(typeof to === 'string' ? { pathname: to } : to);

replaced by var href = this.context.router ? (this.context.router.createHref(typeof to === 'string' ? { pathname: to } : to) ):to;   in order to avoid null pointer in this.context.router

But i will try solution mentioned in #34

**Comment by jose-rafael-marcano** [comment]
#34 It didn't work for me 

I had to add "react-router": "4.0.0-beta.7" in addition to current dependencies, but now I am not getting the sign in or register option. It is displaying Case Studies, APIs and Getting Started, but not register/login options. I am wondering if this is related to cache.  Please @brettstack help out.


![image](https://cloud.githubusercontent.com/assets/23706030/23773261/425886aa-04d3-11e7-900a-9342f3f44018.png)

**Comment by jose-rafael-marcano** [comment]
I found the issue, it was a problem with my package.json. I had to add "react-router": "4.0.0-beta.7", in addition to "react-router-dom": "4.0.0-beta.7".
Thanks
