### ISSUE TITLE
"Try it out" requests do not replace AWS greey path templates with the entered value

### ISSUE THREAD

**Issue by bassmanitram** [awslabs/aws-api-gateway-developer-portal#37]
OpenAPI/Swagger doesn't yet have a "greedy" path parameter syntax (to swallow "the rest of the path")

AWS does: {rest-of-path+}

When trying to enter values for this type of template in the generated swagger UI they are not replaced in the ensuing request - the request goes to https://api-host-name/env/resource/{rest-of-path+}.

**Comment by rpgreen** [comment]
Thanks for reporting. I believe this will be addressed in Swagger 3.0.

It's not likely that will we customize Swagger UI for this - you will be responsible for updating your API docs/testing tools.

**Comment by bassmanitram** [comment]
Understood (though OpenAPI is not including greedy URL path parameters in version 3 - maybe the next version after that)
