### ISSUE TITLE
Left menu items don't react on click

### ISSUE THREAD

**Issue by mseest** [awslabs/aws-api-gateway-developer-portal#376]
I have deployed the developer portal and added a few APIs. Though the left menu items don't react on click and change content in the main view.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/456329/78381008-058f9080-75d5-11ea-8f10-6792a9fe1f60.png">

**Comment by amichot** [comment]
I am having the same issue

**Comment by amazon-meaisiah** [comment]
Try replicating this on the `staging` branch - that should contain a fix for this. We've moved our most recent development work there, and we plan to merge that back to `master` once it's ready.

**Comment by amichot** [comment]
@amazon-meaisiah 
I'm having the same issue with the staging branch.

**Comment by AnjaneyalnDatla** [comment]
Facing the same issue using the github code.It works normally using Serverless Application Repo. 
Do the two have the same code?

**Comment by amazon-meaisiah** [comment]
@AnjaneyalnDatla `master` is not currently in sync with SAR and contains several subsequent commits. Our active work is currently on the `staging` branch, with plans to eventually merge it to `master`, but it was created after initially making some commits to `master` itself.

If you want stability while still using what's in the repo, my recommendation for now is to [use the latest release](https://github.com/awslabs/aws-api-gateway-developer-portal/tree/v3.0.2).

**Comment by AnjaneyalnDatla** [comment]
Thanks @amazon-meaisiah . I tried the version you had suggested(V3.0.2) and seems like its using nodejs8.10 which isn't supported anymore, bumped the version to nodejs12 to see if that works but no luck. StaticAssetUploader function is failing - **Custom Resource failed to stabilize in expected time**

We are currently constrained in our ability to use SAR(we need to provide mandatory tags).So kind of stuck with SAM deployment.Can you point me to the branch version/tag which SAR is currently using. Thanks in advance

**Comment by amazon-meaisiah** [comment]
My mistake - try [this commit](https://github.com/awslabs/aws-api-gateway-developer-portal/tree/348516bb82cebfb693392c73035d61963f1b1968). That is the version SAR is currently using, and that updates all the Node 8 references to Node 12 in a maintenance release. Does that help?

**Comment by amazon-meaisiah** [comment]
Should be fixed in v4.0.0, as I was able to reproduce it and then fixed it.
