### ISSUE TITLE
OPTIONS and HEAD don't have "Try it out!" buttons

### ISSUE THREAD

**Issue by bassmanitram** [awslabs/aws-api-gateway-developer-portal#38]
How can I make these appear?

Thx

**Comment by bassmanitram** [comment]
(It appears that the "sandbox_header" div isn't being inserted into the "sandhox" form for these HTTP methods)

**Comment by brettstack** [comment]
If OPTIONS and HEAD exist on your API, this will likely be an issue with swagger-ui. Check this out https://github.com/swagger-api/swagger-ui/issues/1847

**Comment by bassmanitram** [comment]
And there it is - the swagger default actually DOES include options (not head). dev-portal/public/index.html overrides that, but appears to not be the source of supportedSubmitMethods for this deployment. Any idea where to find that in this use?

Thanks for the help.

**Comment by bassmanitram** [comment]
And there it is - the swagger default actually DOES include options (not head). dev-portal/src/services/swagger-ui.js holds the  the source of the supportedSubmitMethods property for this deployment. I modified that and it's fixed.

Thanks for the help.
