### ISSUE TITLE
Missing instructions how to debug the portal

### ISSUE THREAD

**Issue by okigan** [awslabs/aws-api-gateway-developer-portal#384]
Missing instructions how to debug the portal front end and/or backend (when running locally)

**Comment by okigan** [comment]
Checking in

**Comment by amazon-meaisiah** [comment]
For the front end, you can just open the developer tools and call it a day. For the backend, we do not currently have an easy mechanism to attach a debugger to it outside testing, though you can just run `npx --inspect-brk jest --runInBand` within `lambdas/`, pop open Chrome's dev tools, and click the Node logo to open a separate window for that to accomplish that during testing.

I have not tried running SAM locally with this project (though [it's possible in theory](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-start-api.html)), so I'm not entirely sure if/how that would work.

**Comment by amazon-meaisiah** [comment]
Now fixed: https://github.com/awslabs/aws-api-gateway-developer-portal/blob/master/BUILDING.md
