### ISSUE TITLE
Check the command separators in win-delete-artifacts-bucket

### ISSUE THREAD

**Issue by marjanSterjev** [awslabs/aws-api-gateway-developer-portal#4]
Please check the command separators in win-delete-artifacts-bucket. 

The execution fails at the moment.

**Comment by brettstack** [comment]
Thanks for the report -- I'll get this fixed. For now you can manually create your artifacts bucket.

**Comment by brettstack** [comment]
Could you post the error you're getting? This works fine for me when running win-setup.

**Comment by brettstack** [comment]
Disregard, I thought you were talking about the create step
