### ISSUE TITLE
Unable to register/subscribe

### ISSUE THREAD

**Issue by Jinoooo** [awslabs/aws-api-gateway-developer-portal#40]
I had to apply the changes based on #39 

By applying the change in #39, I was able to deploy the portal successfully.  However `Register `action did spin for ever although I could see the user in Congnito User pool, DevPortal successfully created.
Upon `signin`, it complained the user doesn't exist. 
I applied the following to fix it (not sure why it worked):
`$ npm run post-setup`

Now I am facing two issues:
> Unable to see PetStore API in API Gateway.  Shouldn't it be created by running $ npm run setup
> Unable to subscribe to PetStore API.

It would be great to have a fully functional live demo somewhere to try it out and understand the supported functionalities.

**Comment by Jinoooo** [comment]
Any suggestions?

**Comment by themucha** [comment]
Have you run ```npm run package-deploy```?

**Comment by Jinoooo** [comment]
Yes, I did.  Still having the same problem.

**Comment by brettstack** [comment]
This repo does not create an API for you, though we will consider doing that.

**Comment by Trial-In-Error** [comment]
Closing this; I don't believe we should be creating/exposing an API by default, although I would like to hear good use cases (just re-open this). I can expand on the `README.md` to make it explicit that an existing API is necessary.
