### ISSUE TITLE
Invalid endpoint: https://s3.$npm_package_config_primaryAwsRegion.amazonaws.com

### ISSUE THREAD

**Issue by jayyousi** [awslabs/aws-api-gateway-developer-portal#41]
Hi

I have cloned the project locally and ran the command "npm run setup"" and I'm receiving the following error 
Invalid endpoint: https://s3.$npm_package_config_primaryAwsRegion.amazonaws.com

I have attached some files for more infromtion
[console_output.txt](https://github.com/awslabs/aws-api-gateway-developer-portal/files/888127/console_output.txt)
[2017-04-02T01_18_43_098Z-debug.txt](https://github.com/awslabs/aws-api-gateway-developer-portal/files/888129/2017-04-02T01_18_43_098Z-debug.txt)

**Comment by themucha** [comment]
Hello,
Based on the log files you attached, it looks like you're running on windows.

Since you're running on Windows, you have to use the Windows version of the setup script by running `npm run win-setup`. Please let me know if that fixes the problem that you are encountering.

-Mark

**Comment by jayyousi** [comment]
Thanks for the update

your suggestion fixed the issue

thanks a million
