### ISSUE TITLE
DynamoDB Integration

### ISSUE THREAD

**Issue by brennanerbz** [awslabs/aws-api-gateway-developer-portal#42]
I see that you're using DynamoDB in the customers controller, but I don't see a config for that in any of the yamls. Can you clarify how that's being integrated?

**Comment by brettstack** [comment]
https://github.com/awslabs/aws-api-gateway-developer-portal/blob/master/cloudformation/base.yaml#L57

**Comment by brennanerbz** [comment]
You're the man. Thank you.

**Comment by brettstack** [comment]
Glad to help
