### ISSUE TITLE
Can custom-content folder contain additional items?

### ISSUE THREAD

**Issue by steve-be-old** [awslabs/aws-api-gateway-developer-portal#420]
Hello,
I have been reading through this page on customizations:
https://github.com/awslabs/aws-api-gateway-developer-portal/wiki/Customization#advanced-customization

I believe I understand, I can update GettingStarted.md, Home,md, etc here and a subsequent deploy will not overwrite them if I don't set "overwrite-content".

If I create my own advanced customization, such as a new page with new text, can I create folders here and place content as well, and it will not be overwritten either?  Thinking if I have a file here with text, and I want to quickly update the text without a deploy, update it here and invalidate the cache, it should show up.  

Am I thinking correctly on this?  

Lastly, is there a more appropriate place to ask general questions like this, I'll be happy to ask there.
Thanks.

**Comment by amazon-meaisiah** [comment]
@steve-be-old This is correct. Any file with that prefix will be retained.

And questions like this are okay to post here - we welcome them.

**Comment by steve-be-old** [comment]
Appreciate the quick response, thank you.
