### ISSUE TITLE
Get "Task errored: release Cannot read property 'push' of undefined" while trying to run /dev-portal locally 

### ISSUE THREAD

**Issue by RickLee83** [awslabs/aws-api-gateway-developer-portal#433]
Hi. Am following the guide in:
https://github.com/awslabs/aws-api-gateway-developer-portal/blob/master/BUILDING.md#staticassetrebuildmode-string

I get the following error message upon running the command "Run `node run install release`." mentioned in Step 5.

The error is as below:
Task errored: release
Cannot read property 'push' of undefined

Can anyone share what is the cause I'm getting the error message above??

**Comment by amazon-meaisiah** [comment]
Could you include a full stack trace?

**Comment by RickLee83** [comment]
HI @amazon-meaisiah , after a few round of search on all the Issues that related to mine I found that my project code (Clone from master branch from here) is missing a few files that is needed in order to run `node run install release` command with no error.

As mentioned in issue number 170 (https://github.com/awslabs/aws-api-gateway-developer-portal/pull/170) it seems like there are changes made in /dev-portal folder to run the Developer Portal UI locally.

Below link is the link to the branch (4dbbec4) mentioned in issue number 170:
https://github.com/awslabs/aws-api-gateway-developer-portal/tree/4dbbec42399eff3d4280e373c9c6ac35db80f123/dev-portal

My question is why is this branch change is not yet merged into master branch (since 5 Dec 2018)?? Is there an issue from the changes in this branch??

**Comment by RickLee83** [comment]
Closing this issue as I've got the problem solved.
