### ISSUE TITLE
Make API's visible only to specific users and invisible to others

### ISSUE THREAD

**Issue by rahulbreezo** [awslabs/aws-api-gateway-developer-portal#438]
I have a lot of APIs with multiple usage plans.
I know we can hide/show API's in the dev portal API dashboard  but it affects all users equally like either all users will see API's or no one.

I want to hide/show APIs on the user level. Like show  API's only to few users but not to others. 

Please guide me on how to achieve this.

**Comment by kvidhani** [comment]
There is no way to do this afaik. I got around this by deploying developer portals per each of my customers. A horrible solution but I have no other choice :/

**Comment by rahulbreezo** [comment]
@kvidhani  I was able to do something like that by dividing users based on groups in cognito user pool and then returning only specific API's in front-end depending upon users user group.

A little better way might be using dynamoDb table
