### ISSUE TITLE
Changes to custom-content images aren't deployed to the static assets bucket

### ISSUE THREAD

**Issue by ngalchemist** [awslabs/aws-api-gateway-developer-portal#459]
Dev Portal **version v3.0.6**

My changes aren't uploaded to the static assets bucket, even when passing the StaticAssetRebuildToken in the `sam deploy` command.

Replication steps:

1. Package:

> sam package --template-file ./cloudformation/template.yaml
>     --output-template-file ./cloudformation/packaged.yaml
>     --s3-bucket <bucket_name>

2. Deploy:

> sam deploy --template-file ./cloudformation/template.yaml --stack-name dev-portal
>     --s3-bucket <bucket_name>
>     --capabilities CAPABILITY_NAMED_IAM
>     --parameter-overrides
>     DevPortalSiteS3BucketName=<bucket_name>
>     ArtifactsS3BucketName=<artifacts_bucket_name>
>     CognitoDomainNameOrPrefix=<cognito_prefix>

3. Overwrite /dev-portal/public/custom-content/nav-logo.png locally.
4. Deploy again:

> sam deploy --template-file ./cloudformation/template.yaml --stack-name dev-portal
>     --s3-bucket <bucket_name>
>     --capabilities CAPABILITY_NAMED_IAM
>     --parameter-overrides
>     DevPortalSiteS3BucketName=<bucket_name>
>     ArtifactsS3BucketName=<artifacts_bucket_name>
>     CognitoDomainNameOrPrefix=<cognito_prefix>
>     StaticAssetRebuildToken=<some_uuid>

When I check the static assets bucket (DevPortalSiteS3BucketName) the files from the initial deployment are still present.

**Comment by amazon-meaisiah** [comment]
The readme's instructions are incorrect and need updated. You'll need to [rebuild the assets manually](https://github.com/awslabs/aws-api-gateway-developer-portal/blob/master/BUILDING.md#node-run-build) and then deploy.

**Comment by amazon-meaisiah** [comment]
Update: I misread your version number. Here's what you'll need to do for v3.x:

1. If you haven't installed Node, you'll need to do so.
2. Open a terminal, navigate to the `dev-portal` directory of your repo.
3. Run `npm install` then `npm run build`.
4. Then try deploying again.

Sorry about that!
