### ISSUE TITLE
marketplace-subscriptions doesn't actually use the usagePlanId

### ISSUE THREAD

**Issue by orasis** [awslabs/aws-api-gateway-developer-portal#46]
The usagePlanId appears to be dead code there.  You might want to clean up.

**Comment by plutext** [comment]
/marketplace-subscriptions is used at 
https://github.com/aws-samples/aws-api-gateway-developer-portal/blob/master/dev-portal/src/services/api-catalog.js#L79

Where is this end point documented?   It doesn't seem to be part of https://docs.aws.amazon.com/apigateway/api-reference/resource/

**Comment by Trial-In-Error** [comment]
Yep! There's [an issue](https://github.com/awslabs/aws-api-gateway-developer-portal/issues/23) for the marketplace integration that this will get cleaned up as part of. Closing.
