### ISSUE TITLE
Race condition with subscribe-success?

### ISSUE THREAD

**Issue by orasis** [awslabs/aws-api-gateway-developer-portal#47]
The way subscribe-success is implemented, it requires createMarketPlaceSubscription to be called first in order to set up the cognito id <-> customerId mapping.  I see nothing in createMarketPlaceSubscription or subscribe-success that ensures this ordering.

What is the timing of subscribe-success being called?  Does resolveCustomer trigger it?  Is it just on some time delay after the customer presses subscribe in the portal?

**Comment by rpgreen** [comment]
subscribe-success is triggered by an SNS notification from marketplace. The only way this notification could be sent is if a customer successfully completes the marketplace subscription workflow, which includes resolveCustomer and writing to DDB. Of course, there is a possibility that something could go wrong during this step, so it wouldn't be a bad idea to handle the case when the customer doesn't exist in the data store. It would be up to your application to determine what to do in this case.

**Comment by orasis** [comment]
The writing to DDB happens after resolveCustomer, so if subscribe-success is triggered by resolveCustomer in the marketplace it seems possible that the DDB write and the subscribe-success SNS could race.

**Comment by orasis** [comment]
Actually.  I just tested this on a pre-release product and the SNS "subscribe-success" fires immediately when the user presses subscribe on the market place without waiting for any of the marketplace-confirm flow to run.

Now, I've been re-using this user for testing, unsubscribing and re-subscribing so perhaps the subscribe-success is firing immediately in this case, before we've even had a chance to handle marketplace-confirm.  

I don't really have a way to test with a fresh user at the moment.

**Comment by orasis** [comment]
Okay, it looks like you create an api key in both paths if one doesn't already exist, allowing the subscribe-success and marketplace-subscriptions to occur in any order.  This was totally unclear to me.

**Comment by orasis** [comment]
If the subscribe-success listener is triggered first, then controller.getCognitoIdentityId won't return anything and subscribe will never be called.

**Comment by rpgreen** [comment]
It sounds like this race condition could be possible and this case should be handled.

In the event that the event is received before the workflow completes, the event will need to be queued and retried until the customer ID is persisted. The case should be handled as well when the customer ID is never persisted, but this behavior should probably be specific to your use-case.

This solution could be achieved pretty simply with a separate SQS queue and a scheduled Lambda function. If the listener function cannot find the customer, it enqueues the event in SQS. The scheduled Lambda function polls the queue, looks for the customer, and deletes the message if the customer is located in DDB. Eventually after a number of retries (stored in DDB?) the function should delete the message and some action should be taken.

If you can get this solution working a PR would be appreciated.

**Comment by orasis** [comment]
The workaround I've implemented is to create an api-key in the
subscribe-success with the customerId and usage plan but no reference to
the cognitoId.  Then, in createMarketplaceSubscription the api key is
looked up by customerId and associated with the cognitoId at that point.
So basically both sides of the transaction create and update with whatever
information they have available.

My code has evolved to be far far different from the sample (promises, no
dynamodb, one usage plan), so I can't do a PR.

**Comment by orasis** [comment]
By the way, thanks so much for the template.  This would have been near impossible without this example.  I'm happy to paste my promise-based code if its useful to you.

**Comment by brettstack** [comment]
A PR for our reference may be useful.

**Comment by Trial-In-Error** [comment]
Appears to be fixed. Closing.
