### ISSUE TITLE
Clean script does not delete the API Keys created

### ISSUE THREAD

**Issue by marjanSterjev** [awslabs/aws-api-gateway-developer-portal#5]
The clean script drops everything but the API Keys created. 

Is there particular reason for not doing that?

**Comment by brettstack** [comment]
Thanks for bringing this up. For now we will call this out in the README that API Keys must be cleaned up manually. We will add an action item to implement this as a script you can run on cleanup.

**Comment by rpgreen** [comment]
The clean script should only tear down things created by the setup scripts or cloudformation stack. We may want to implement a separate script to delete user data such as API Keys.

**Comment by Trial-In-Error** [comment]
Agree that the clean script shouldn't delete the API Keys. I'll add a section to the readme.
