### ISSUE TITLE
Browser issue - Dev portal doesn't work on Internet explorer 

### ISSUE THREAD

**Issue by maheshlovetesting** [awslabs/aws-api-gateway-developer-portal#51]
Hi, We use AWS api gate way Dev Portal to publish our api.

Issue is doesn't work on Internet explorer please help.
![dev portal on internet explorer click on api you get this screen](https://user-images.githubusercontent.com/25887775/27058373-fde0e4e8-5024-11e7-862f-dcdb7fb2bc59.PNG)

**Comment by brettstack** [comment]
Thanks for the report. I'll take a look. What version of IE?

**Comment by maheshlovetesting** [comment]
Thanks @brettstack IE version 11. We use swagger for publication. That part doesn't work

**Comment by brettstack** [comment]
What error are you getting?

**Comment by maheshlovetesting** [comment]
Go to IE type https://api.doc.govt.nz/ 

go to discover click on campsite or huts and get the following 

see console 

Possible Unhandled Promise Rejection (id: 1): 
Possible Unhandled Promise Rejection (id: 0):
  TypeError: Object doesn't support property or method 'find'
     at Anonymous function (https://api.doc.govt.nz/static/js/main.5a59acec.js:4:16738)
     at Anonymous function (https://api.doc.govt.nz/static/js/main.5a59acec.js:4:16705)
     at o (https://api.doc.govt.nz/static/js/main.5a59acec.js:14:23541)
     at Anonymous function (https://api.doc.govt.nz/static/js/main.5a59acec.js:14:24285)
     at n (https://api.doc.govt.nz/static/js/main.5a59acec.js:31:18567)
SEC7118: XMLHttpRequest for https://ail07qogfl.execute-api.ap-southeast-2.amazonaws.com/prod/subscriptions?end=undefined&start=undefined required Cross Origin Resource Sharing (CORS).
File: apis
SEC7119: XMLHttpRequest for https://ail07qogfl.execute-api.ap-southeast-2.amazonaws.com/prod/subscriptions?end=undefined&start=undefined required CORS preflight.
File: apis
SEC7118: XMLHttpRequest for https://ail07qogfl.execute-api.ap-southeast-2.amazonaws.com/prod/subscriptions?end=undefined&start=undefined required Cross Origin Resource Sharing (CORS).
File: apis
SEC7119: XMLHttpRequest for https://ail07qogfl.execute-api.ap-southeast-2.amazonaws.com/prod/subscriptions?end=undefined&start=undefined required CORS preflight.
File: apis
Possible Unhandled Promise Rejection (id: 1):
  TypeError: Object doesn't support property or method 'find'
     at Anonymous function (https://api.doc.govt.nz/static/js/main.5a59acec.js:4:16738)
     at Anonymous function (https://api.doc.govt.nz/static/js/main.5a59acec.js:4:16705)
     at o (https://api.doc.govt.nz/static/js/main.5a59acec.js:14:23541)
     at Anonymous function (https://api.doc.govt.nz/static/js/main.5a59acec.js:14:24285)
     at n (https://api.doc.govt.nz/static/js/main.5a59acec.js:31:18567)

**Comment by maheshlovetesting** [comment]
Works file on chrome

**Comment by brettstack** [comment]
> Object doesn't support property or method 'find'

IE11 doesn't support `Array.prototype.find`. I'll get this patched in the repo as soon as I get better access to a Windows machine. For now, you should be able to resolve this by:

1. Install `babel-polyfill` in the `/dev-portal` directory

```shell
npm install --save babel-polyfill
```

2. Add to the top of `/dev-portal/src/index.js`

```js
import 'babel-polyfill'
```

`babel-polyfill` is quite a lot of code, and you're better off polyfilling only what you need. Here's an `Array.prototype.find` polyfill on MDN https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find?v=example#Polyfill. If you go this route, make sure you include it before it's used.

**Comment by maheshlovetesting** [comment]
Thanks a lot I will let my developer know @brettstack anymore suggestions most welcome 

Cheers,
Mahesh

**Comment by brettstack** [comment]
No problem. Leaving this open until we get it patched in the repo.

**Comment by maheshlovetesting** [comment]
Thanks

**Comment by maheshlovetesting** [comment]
Hey our developer fix the issue according to you instructions cheers

**Comment by Trial-In-Error** [comment]
Closing; v1 specific, and looks like customer resolved their issue. :)
