### ISSUE TITLE
CloudFormation fails at CloudFrontSecurityHeadersSetup

### ISSUE THREAD

**Issue by Just-Drue** [awslabs/aws-api-gateway-developer-portal#519]
When deploying it fails at `CloudFrontSecurityHeadersSetup` step and unsure why.

![Screenshot 2021-11-23 at 14 24 22](https://user-images.githubusercontent.com/46595021/143023891-dad69b2a-692f-4e18-a025-d5322056cfc5.png)

Looked through open and closed issues but haven't found any similar tickets.
Tried in multiple regions (`us-west-1` and `eu-west-1`)

EDIT: Tried downloading repo and following [this guide](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-developer-portal.html) but the result is the same.
EDIT#2: Downgrading to 4.0.4 didn't solve it as well.
EDIT#3: Following [this guide](https://aws.amazon.com/blogs/networking-and-content-delivery/managing-lambdaedge-and-cloudfront-deployments-by-using-a-ci-cd-pipeline/) and setting everything to `us-east-1` doesn't help as well.

**Comment by mklint** [comment]
For an **awful** workaround, try adding `await new Promise(resolve => setTimeout(resolve, 15000))` BEFORE this line: https://github.com/awslabs/aws-api-gateway-developer-portal/blob/cd1ea9451d4ed1cfbe6719f26f7f941f6a8285e9/lambdas/cloudfront-security/replicator.js#L67

Deployment succeeded, unsure of any unforeseen consequences.

**Comment by jweyrich** [comment]
Exact same problem here.

**Comment by axthosarouris** [comment]
Same problem in eu-west-1

**Comment by gmmarc** [comment]
Same problem in eu-north-1. The same code I'm using used to work in March 2021. I believe this is related to an update on July 2021:
> Pending – After Lambda creates the function, it sets the state to pending. While in pending state, Lambda attempts to create or configure resources for the function, such as VPC or EFS resources. Lambda does not invoke a function during pending state. Any invocations or other API actions that operate on the function will fail.
Source: https://docs.aws.amazon.com/lambda/latest/dg/functions-states.html

The following worked for me too. Thx @mklint !

> For an **awful** workaround, try adding `await new Promise(resolve => setTimeout(resolve, 15000))` BEFORE this line:
> 
> https://github.com/awslabs/aws-api-gateway-developer-portal/blob/cd1ea9451d4ed1cfbe6719f26f7f941f6a8285e9/lambdas/cloudfront-security/replicator.js#L67

**Comment by bogartlisa** [comment]
sam issue here us-east-1

**Comment by philcaixeta** [comment]
Thanks for reporting this. The update we had around Lambda Function States caused this issue. We need to wait for the newly created/updated function to be `Active` before doing any operations with it, like publishing. Since this is an async call, the workaround mentioned here would help if the time was enough, thanks for the help!

This issue was fixed and the code merged with this [PR](https://github.com/awslabs/aws-api-gateway-developer-portal/pull/520), by adding `waiter` functions until the correct state was set.

**Comment by mahadevancloudmaster** [comment]
Still getting the same error, how to fix it?
