### ISSUE TITLE
Getting Limit exceeded for resource of type 'AWS::CloudFront::Distribution

### ISSUE THREAD

**Issue by anil1712** [awslabs/aws-api-gateway-developer-portal#526]
I am trying to setup AWS API Gateway Developer Portal into as localhost, but getting following exception

```
"Limit exceeded for resource of type
'AWS::CloudFront::Distribution'.
Reason: Completing this action would
cause the maximum number of
distributions with Lambda function
associations per owner to be exceeded
(maximum allowed is 25).
```

Can anyone provide any solution for this?

**Comment by aws-amit** [comment]
There is quota limit documented [here](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-lambda-at-edge)
Possible solutions: 
1. Cleanup unused associations
2. Request a higher quota
