### ISSUE TITLE
Uploading swagger docs using the CLI

### ISSUE THREAD

**Issue by foxbox-doug** [awslabs/aws-api-gateway-developer-portal#534]
Per this [blog post](https://aws.amazon.com/blogs/compute/deploying-a-personalized-api-gateway-serverless-developer-portal/), you can use the following command to push a swagger doc to the portal:

```
aws s3 cp apiId_stageName.json s3://yourBucketName/catalog/apiId_stageName.json
```

However, it does not appear that there is a role that can be assumed that gives permissions to push to this S3 bucket.

**Comment by aws-amit** [comment]
Please make sure the role that is being used to perform this operation has sufficient permissions. 
Eg. https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-policies-s3.html#iam-policy-ex0
