### ISSUE TITLE
/apis when not logged is just spinning

### ISSUE THREAD

**Issue by smita30apr** [awslabs/aws-api-gateway-developer-portal#535]
I want to show the apis when the user is not logged in so that the user can play with this. Is that possible? And when the user likes and wants to actually use them they can register themselves and get an api key. Is that possible?

**Comment by philcaixeta** [comment]
Thanks for your message!
Unfortunately that's not possible. We need the login tokens to be able to access those API's for security reasons. A possible solution for you, at least for now, would be creating your own playground webpage.
