### ISSUE TITLE
Any plans to update to the latest swagger 3.1.1

### ISSUE THREAD

**Issue by jayyousi** [awslabs/aws-api-gateway-developer-portal#55]
Any plans to update to the latest swagger 3.1.1
https://www.npmjs.com/package/swagger-ui

**Comment by brettstack** [comment]
I'll look into it. If you beat me to it, feel free to submit a PR 👍

**Comment by Trial-In-Error** [comment]
Hi! We have a new version of the developer portal on master that now uses swagger UI 3. Closing for now; feel free to try out the new version of the developer portal (it's way easier to deploy) and let us know what you think!
