### ISSUE TITLE
Cannot have a working version following the readme

### ISSUE THREAD

**Issue by dawez** [awslabs/aws-api-gateway-developer-portal#57]
I am following the readme to have a working developer portal however it seems that I am facing an issue in the setup:

when I launch `npm run setup` after the process is complete the browser opens with the page:

http://MYPORTALNAME-app.s3-website-eu-central-1.amazonaws.com

and this one I get 404. The correct address would be instead:

http://MYPORTALNAME-app.s3-website.eu-central-1.amazonaws.com

At this address I can see at least the default page. [note that the empty one is using website-eu while the one that has content has website.eu] 

The region I chose was "eu-central-1"

Also I cannot see the api if I go in this page: 

http://MYPORTALNAME-app.s3-website.eu-central-1.amazonaws.com/apis and then I've some error in the console

> apis:1 Uncaught (in promise) {data: "", status: 0, statusText: "", headers: {…}, config: {…}}config: {method: "GET", headers: {…}, timeout: 0, transformRequest: Array(1), transformResponse: Array(1), …}data: ""headers: {}status: 0statusText: ""__proto__: Object
Promise rejected (async)

steps that I did: 

- create  a developer portal in amazon
- clone this repository
- change the index.js in the lambdas/backend/catalog/ and replaced : YOUR_USAGE_PLAN_ID with 'beta' the stage I used in the developer portal and 'YOUR_API_ID', with the one that I got between parenthesis on top of the page [see attached screenshot]
- launched npm run setup
![selection_066](https://user-images.githubusercontent.com/2534771/28920749-652e8afa-7853-11e7-868c-61d00ec90f23.png)

**Comment by zachdb86** [comment]
Please look at issue #54

**Comment by turacma** [comment]
Thanks for the feedback. It looks like we have an issue tracking the path issue.

Regarding the configuration you've set up. What you're pointing to as "YOUR_USAGE_PLAN_ID" is not in fact a Usage Plan. This is an API Stage. You will need to actually configure a Usage Plan and use this plans ID instead.

**Comment by Trial-In-Error** [comment]
This issue should be fixed in the v2 (SAM deployed) dev portal (the URLs will be the result of the CFN deployment). I'm closing this.
