### ISSUE TITLE
Out of the Box: Will not load API page

### ISSUE THREAD

**Issue by benstoehr** [awslabs/aws-api-gateway-developer-portal#58]
Hello. 

I am trying to get my API up and available through this Developer Gateway. When I start from scratch (clone the repo as is), and run "npm run setup", the Developer Portal homepage shows up. However, the URL is

http://dpwa.s3-website-us-east-1.amazonaws.com/ 

and not 

http://dpwa.s3-website.us-east-1.amazonaws.com/

This was an issue addressed in #57. It is also addressed in #54, but the solution from the second answer doesn't explain where they changed the website URL. 

When I navigate to the /apis page, I have a few errors appear in the console. 

<img width="937" alt="screen shot 2017-09-22 at 3 47 49 pm" src="https://user-images.githubusercontent.com/8814009/30763788-880b9ff0-9fad-11e7-8c71-ddd6002b6fbc.png">

I am trying to find out if this is an error that has to do with the Buckets that I created in the "npm run setup" step or this is an error from the current branch. 

I have followed the steps in both #57 and #54, doing only one or only the other, doing both, starting from scratch. No matter what I try, the API page will not load. 

I appreciate any feedback.
Thank You

**Comment by MynockSpit** [comment]
Looks like the S3 bucket set up doesn't allow that origin. Check your cloudformation YAML; what does your WebsiteS3Bucket HostName (line 49-54) look like? Here's what it should look like for us-east-1.

```yaml
HostName: !Join
  - ''
  - - !Ref DevPortalSiteS3Bucket
    - .s3-website-
    - !Ref 'AWS::Region'
    - .amazonaws.com
```

**Comment by benstoehr** [comment]
I have that along with an extra bit about ReplaceKeyPrefixWith: '#/!' 

<img width="525" alt="screen shot 2017-10-02 at 11 25 33 am" src="https://user-images.githubusercontent.com/8814009/31087904-72cca198-a764-11e7-845a-f5fd79262055.png">

**Comment by MynockSpit** [comment]
Okay, good. Check one other place. Go to [S3](https://s3.console.aws.amazon.com/s3/home?region=us-east-1) then click on your bucket, select the Properties tab, then click Static Website Hosting. Should look something like this:

<img width="656" alt="screen shot 2017-10-02 at 10 07 06 am" src="https://user-images.githubusercontent.com/5713867/31089689-e1b6ac44-a759-11e7-9850-8eee06242f6a.png">

**Comment by benstoehr** [comment]
I do get this. The "Use bucket to . . ." was already checked

<img width="546" alt="screen shot 2017-10-03 at 1 18 32 pm" src="https://user-images.githubusercontent.com/8814009/31141583-6b86817c-a83d-11e7-8837-b36e898dc36b.png">

This is the redirection rules:
<RoutingRules>
  <RoutingRule>
    <Condition>
      <KeyPrefixEquals/>
      <HttpErrorCodeReturnedEquals>404</HttpErrorCodeReturnedEquals>
    </Condition>
    <Redirect>
      <HostName>dpwa.s3-website-us-east-1.amazonaws.com</HostName>
      <ReplaceKeyPrefixWith>#!/</ReplaceKeyPrefixWith>
    </Redirect>
  </RoutingRule>
</RoutingRules>

Do you think this could be easily fixed by changing my default region?

Ben

**Comment by dchrostowski** [comment]
I'm having the same exact issue.  Any information to get this working?

**Comment by Trial-In-Error** [comment]
Hi! We have a new version of the developer portal on master that is deployed in an entirely different fashion. I'm closing this; if you have any issues with the new developer portal, please open a fresh issue. Thanks!
