### ISSUE TITLE
502 error

### ISSUE THREAD

**Issue by pshettyk** [awslabs/aws-api-gateway-developer-portal#59]
I am facing issue as getting Error 502 (Bad gateway) while 'Register' and clicking on 'ÁPIs'.
After Signin call, it will show 502 error. And popup wont close.
Similarly if I click on 'APIs' link in home page.  Same 502 error.

**Comment by noisygerman** [comment]
This seems to be a deployment or build problem:

```
{
    "errorMessage": "Cannot find module 'common-lambda-assets/customers-controller.js'",
    "errorType": "Error",
    "stackTrace": [
        "require (internal/module.js:12:17)",
        "Object.<anonymous> (/var/task/express-server.js:10:29)",
        "Module._compile (module.js:409:26)",
        "Object.Module._extensions..js (module.js:416:10)",
        "Module.load (module.js:343:32)",
        "Function.Module._load (module.js:300:12)",
        "Module.require (module.js:353:17)"
    ]
}
```

in `lambdas/backend/express-server.js`

**Comment by noisygerman** [comment]
Looks like this is a npm 5+ change. `npm uninstall` to remove dependencies. I'll see if I can fix this

**Comment by brettstack** [comment]
See the latest PR

**Comment by bejos** [comment]
Fixed in https://github.com/awslabs/aws-api-gateway-developer-portal/pull/61
