### ISSUE TITLE
Usage Plans, API and Marketplace Product Code Relations

### ISSUE THREAD

**Issue by marjanSterjev** [awslabs/aws-api-gateway-developer-portal#6]
With the latest changes introduced, in the API Gateway Usage Plans we can configure:

1.	Multiple API/Stages assigned to the Usage Plan
2.	Multiple API Keys assigned to the Usage Plan
3.	Single Marketplace Product Code

The Usage Plan definition is: 

“_…A usage plan provides access to one or more deployed API stages with configurable throttling and quota limits enforced on individual client API keys… Throttling and quota limits apply to requests for individual API keys that are aggregated across all API stages within a usage plan…._”

So it seems the relation Marketplace Product Code/API(Stages) is **one-to-many**.

However, in both blogs:

https://aws.amazon.com/blogs/compute/generate-your-own-api-gateway-developer-portal/

https://aws.amazon.com/blogs/compute/monetize-your-apis-in-aws-marketplace-using-api-gateway/

the relation API/Marketplace Product Code is considered as **one-to-one**.

The same is true for the developer portal code because **catalog.json** has an attribute **usagePlanId** and one **swagger** attribute  (not many). The user interface also enforces subscriptions to a single API. 
Is this intentionally or this is a flaw in the model?

It is not very practical to define the same API in the **catalog.json** multiple times, once per **usagePlanId**. How about **usagePlanIds** array?

It would be nice if customer can search for an API on the Marketplace and select the Usage Plan within the API selected. This is an approach taken by some other API Gateways on the market and it seems to be very convenient from user perspective.

Opinion?

Thank You

**Comment by masuog** [comment]
Thank you for your feedback.  API Gateway currently supports multiple API Stages associated with a given Usage Plan, but there is a **one-to-one** relationship between a Usage Plan and a Product Code.  As for the current Developer Portal reference implementation, this initial release was only intended to illustrate some of the capabilities and we will be looking into exposing the concept of a product (usage plan / product code) with multiple associated API stage that can be metered with single API Key.

Does this address your question?  If not, could you please elaborate on your specific use case you have in mind?

**Comment by marjanSterjev** [comment]
Thank you.

**Comment by blootsvoets** [comment]
I have a similar question: we are developing a personal nutrition platform with data and knowledge rules. We want to price the data and the knowledge rules differently, and thought to have a price differentiation between the two, e.g.

1. data: $ 0.001 / request
2. knowledge rules: $ 0.05 per request

There would be two usage plans:
Data (maps to /data-api)
KnowledgeRules (maps to /knowledge-rule-api)

Is it possible to achieve this with AWS API Gateway + AWS Marketplace? Or is there a simpler way to achieve this?
