### ISSUE TITLE
Will not build on EC2

### ISSUE THREAD

**Issue by mraiser** [awslabs/aws-api-gateway-developer-portal#64]
I launched a T2 Large Ubuntu Server 16.04 LTS instance on EC2, installed node & aws cli, and tried to run the setup but npm complains about missing files while uploading to s3. Is it possible I am missing a library or something?

...
	upload: build/swagger-ui/dist/lib/swagger-oauth.js to s3://getlocodatum/swagger-ui/dist/lib/swagger-oauth.js
	upload: build/swagger-ui/dist/swagger-ui.min.js to s3://getlocodatum/swagger-ui/dist/swagger-ui.min.js
	upload: build/swagger-ui/dist/lang/ja.js to s3://getlocodatum/swagger-ui/dist/lang/ja.js
	upload: build/swagger-ui/dist/lib/lodash.min.js to s3://getlocodatum/swagger-ui/dist/lib/lodash.min.js
	upload: build/swagger-ui/dist/swagger-ui.js to s3://getlocodatum/swagger-ui/dist/swagger-ui.js
	npm ERR! path xdg-open
	npm ERR! code ENOENT
	npm ERR! errno ENOENT
	npm ERR! syscall spawn xdg-open
	npm ERR! enoent spawn xdg-open ENOENT
	npm ERR! enoent This is related to npm not being able to find a file.
	npm ERR! enoent 
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/ubuntu/.npm/_logs/2018-02-20T17_00_35_827Z-debug.log
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! aws-serverless-dev-portal-example@1.0.0 post-setup: `npm run post-config && cd dev-portal && npm install && npm run upload-site && npm home`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the aws-serverless-dev-portal-example@1.0.0 post-setup script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/ubuntu/.npm/_logs/2018-02-20T17_00_35_841Z-debug.log
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! aws-serverless-dev-portal-example@1.0.0 setup: `npm install && npm run pre-config && npm run create-artifacts-bucket && npm run lambdas-npm-install && npm run package-deploy && npm run post-setup`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the aws-serverless-dev-portal-example@1.0.0 setup script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/ubuntu/.npm/_logs/2018-02-20T17_00_35_853Z-debug.log
	ubuntu@ip-172-31-29-194:~/aws-api-gateway-developer-portal$ cat /home/ubuntu/.npm/_logs/2018-02-20T17_00_35_827Z-debug.log
	0 info it worked if it ends with ok
	1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'home' ]
	2 info using npm@5.6.0
	3 info using node@v9.4.0
	4 silly docs [ '.' ]
	5 silly getDoc .
	6 verbose npm-session 1de6a37c14c77707
	7 silly pacote directory manifest for undefined@file: fetched in 11ms
	8 verbose stack Error: spawn xdg-open ENOENT
	8 verbose stack     at _errnoException (util.js:1003:13)
	8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
	8 verbose stack     at onErrorNT (internal/child_process.js:389:16)
	8 verbose stack     at process._tickCallback (internal/process/next_tick.js:152:19)
	9 verbose cwd /home/ubuntu/aws-api-gateway-developer-portal/dev-portal
	10 verbose Linux 4.4.0-1049-aws
	11 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "home"
	12 verbose node v9.4.0
	13 verbose npm  v5.6.0
	14 error path xdg-open
	15 error code ENOENT
	16 error errno ENOENT
	17 error syscall spawn xdg-open
	18 error enoent spawn xdg-open ENOENT
	19 error enoent This is related to npm not being able to find a file.
	20 verbose exit [ 1, true ]
	ubuntu@ip-172-31-29-194:~/aws-api-gateway-developer-portal$ cat /home/ubuntu/.npm/_logs/2018-02-20T17_00_35_841Z-debug.log
	0 info it worked if it ends with ok
	1 verbose cli [ '/usr/local/bin/node',
	1 verbose cli   '/usr/local/bin/npm',
	1 verbose cli   'run',
	1 verbose cli   'post-setup' ]
	2 info using npm@5.6.0
	3 info using node@v9.4.0
	4 verbose run-script [ 'post-setup' ]
	5 info lifecycle aws-serverless-dev-portal-example@1.0.0~post-setup: aws-serverless-dev-portal-example@1.0.0
	6 verbose lifecycle aws-serverless-dev-portal-example@1.0.0~post-setup: unsafe-perm in lifecycle true
	7 verbose lifecycle aws-serverless-dev-portal-example@1.0.0~post-setup: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/aws-api-gateway-developer-portal/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/aws-api-gateway-developer-portal/node_modules/.bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
	8 verbose lifecycle aws-serverless-dev-portal-example@1.0.0~post-setup: CWD: /home/ubuntu/aws-api-gateway-developer-portal
	9 silly lifecycle aws-serverless-dev-portal-example@1.0.0~post-setup: Args: [ '-c',
	9 silly lifecycle   'npm run post-config && cd dev-portal && npm install && npm run upload-site && npm home' ]
	10 silly lifecycle aws-serverless-dev-portal-example@1.0.0~post-setup: Returned: code: 1  signal: null
	11 info lifecycle aws-serverless-dev-portal-example@1.0.0~post-setup: Failed to exec post-setup script
	12 verbose stack Error: aws-serverless-dev-portal-example@1.0.0 post-setup: `npm run post-config && cd dev-portal && npm install && npm run upload-site && npm home`
	12 verbose stack Exit status 1
	12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
	12 verbose stack     at EventEmitter.emit (events.js:160:13)
	12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
	12 verbose stack     at ChildProcess.emit (events.js:160:13)
	12 verbose stack     at maybeClose (internal/child_process.js:943:16)
	12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
	13 verbose pkgid aws-serverless-dev-portal-example@1.0.0
	14 verbose cwd /home/ubuntu/aws-api-gateway-developer-portal
	15 verbose Linux 4.4.0-1049-aws
	16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "post-setup"
	17 verbose node v9.4.0
	18 verbose npm  v5.6.0
	19 error code ELIFECYCLE
	20 error errno 1
	21 error aws-serverless-dev-portal-example@1.0.0 post-setup: `npm run post-config && cd dev-portal && npm install && npm run upload-site && npm home`
	21 error Exit status 1
	22 error Failed at the aws-serverless-dev-portal-example@1.0.0 post-setup script.
	22 error This is probably not a problem with npm. There is likely additional logging output above.
	23 verbose exit [ 1, true ]
	ubuntu@ip-172-31-29-194:~/aws-api-gateway-developer-portal$ cat /home/ubuntu/.npm/_logs/2018-02-20T17_00_35_853Z-debug.log
	0 info it worked if it ends with ok
	1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'setup' ]
	2 info using npm@5.6.0
	3 info using node@v9.4.0
	4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
	5 info lifecycle aws-serverless-dev-portal-example@1.0.0~presetup: aws-serverless-dev-portal-example@1.0.0
	6 info lifecycle aws-serverless-dev-portal-example@1.0.0~setup: aws-serverless-dev-portal-example@1.0.0
	7 verbose lifecycle aws-serverless-dev-portal-example@1.0.0~setup: unsafe-perm in lifecycle true
	8 verbose lifecycle aws-serverless-dev-portal-example@1.0.0~setup: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/aws-api-gateway-developer-portal/node_modules/.bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
	9 verbose lifecycle aws-serverless-dev-portal-example@1.0.0~setup: CWD: /home/ubuntu/aws-api-gateway-developer-portal
	10 silly lifecycle aws-serverless-dev-portal-example@1.0.0~setup: Args: [ '-c',
	10 silly lifecycle   'npm install && npm run pre-config && npm run create-artifacts-bucket && npm run lambdas-npm-install && npm run package-deploy && npm run post-setup' ]
	11 silly lifecycle aws-serverless-dev-portal-example@1.0.0~setup: Returned: code: 1  signal: null
	12 info lifecycle aws-serverless-dev-portal-example@1.0.0~setup: Failed to exec setup script
	13 verbose stack Error: aws-serverless-dev-portal-example@1.0.0 setup: `npm install && npm run pre-config && npm run create-artifacts-bucket && npm run lambdas-npm-install && npm run package-deploy && npm run post-setup`
	13 verbose stack Exit status 1
	13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
	13 verbose stack     at EventEmitter.emit (events.js:160:13)
	13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
	13 verbose stack     at ChildProcess.emit (events.js:160:13)
	13 verbose stack     at maybeClose (internal/child_process.js:943:16)
	13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
	14 verbose pkgid aws-serverless-dev-portal-example@1.0.0
	15 verbose cwd /home/ubuntu/aws-api-gateway-developer-portal
	16 verbose Linux 4.4.0-1049-aws
	17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
	18 verbose node v9.4.0
	19 verbose npm  v5.6.0
	20 error code ELIFECYCLE
	21 error errno 1
	22 error aws-serverless-dev-portal-example@1.0.0 setup: `npm install && npm run pre-config && npm run create-artifacts-bucket && npm run lambdas-npm-install && npm run package-deploy && npm run post-setup`
	22 error Exit status 1
	23 error Failed at the aws-serverless-dev-portal-example@1.0.0 setup script.
	23 error This is probably not a problem with npm. There is likely additional logging output above.
	24 verbose exit [ 1, true ]
	ubuntu@ip-172-31-29-194:~/aws-api-gateway-developer-portal$ history
		1  sudo apt-get update
		2  sudo apt-get dist-upgrade -y
		3  curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
		4  sudo apt-get install -y build-essential nodejs python-pip
		5  sudo pip install --upgrade pip
		6  pip install awscli --upgrade --user
		7  aws --version
		8  aws configure
		9  sudo npm i -g npm
	   10  sudo npm i -g n
	   11  sudo n stable
	   12  sudo chown -R $USER:$(id -gn $USER) /home/ubuntu/.config
	   13  git clone https://github.com/awslabs/aws-api-gateway-developer-portal.git
	   14  cd aws-api-gateway-developer-portal/
	   15  npm run setup
	   16  cat /home/ubuntu/.npm/_logs/2018-02-20T17_00_35_827Z-debug.log
	   17  cat /home/ubuntu/.npm/_logs/2018-02-20T17_00_35_841Z-debug.log
	   18  cat /home/ubuntu/.npm/_logs/2018-02-20T17_00_35_853Z-debug.log
	   19  history
	ubuntu@ip-172-31-29-194:~/aws-api-gateway-developer-portal$

**Comment by Trial-In-Error** [comment]
Closing as v2 / SAM deployable is now default, and these install scripts are no longer necessary.
