### ISSUE TITLE
Unable to locate credentials

### ISSUE THREAD

**Issue by aditimp10** [awslabs/aws-api-gateway-developer-portal#65]
Hi All,

I am trying to setup the AWS API Developer portal,I get prompt for account id,s3 bucket name,Cloud Formation name and the moment we input all the data we get error. 
Steps we have followed are as below :
AWS CLI Setup and Configured
Node js Configured
aws configure --profile deeps
npm run win-setup
Error : Unable to Locate credentials.
Pls help.

**Comment by nsellers** [comment]
You probably need to edit the script and add the "--profile deeps" to the aws command.

**Comment by Trial-In-Error** [comment]
Likely that the CLI didn't have a configured credentials file. See [these docs for details](https://docs.aws.amazon.com/cli/latest/userguide/cli-config-files.html). Closing.
