### ISSUE TITLE
License headers

### ISSUE THREAD

**Issue by blootsvoets** [awslabs/aws-api-gateway-developer-portal#67]
The LICENSE in the root of the project states Apache License 2.0, but the license is not applied to any of the files, nor are copyright holders mentioned anywhere. How should this project be mentioned, and who are the actual copyright holders? Could headers be added to the source code files?

**Comment by Trial-In-Error** [comment]
That's a very good question. @a-tan, could you take a look at what the usual practice in AWS OSS-land is for copyright holder? That part of our LICENSE is currently a placeholder... :/

Also, blootsvoets@, I'm not technical on licensing, but it looks like Apache 2.0 [doesn't require a copy of the header in source code files](http://www.apache.org/dev/apply-license.html#copy-per-file) unless that source [is submitted directly to the ASF](http://www.apache.org/legal/src-headers.html#headers). Is that your understanding?

**Comment by a-tan** [comment]
I have added a NOTICE file that mentions the copyright holders.

The placeholder text was part of the Appendix for the license file, I have filled it in as well to remove confusion.  We will also add the license snippet from the Appendix to the header of the files.

**Comment by Trial-In-Error** [comment]
Closed by #123.
