### ISSUE TITLE
Swagger page authenticate with AWS Signature v4.0

### ISSUE THREAD

**Issue by nsellers** [awslabs/aws-api-gateway-developer-portal#69]
Has anyone had experience using the swagger UI in this repo authenticating with AWS Signature v4.0?

**Comment by Trial-In-Error** [comment]
Can you expand on this a little more? I'm unclear what the issue is.

**Comment by Trial-In-Error** [comment]
Closing this issue; haven't heard back from @nsellers, and we've moved to swaggerUI 3.
