### ISSUE TITLE
Can't customize Api Response Headers

### ISSUE THREAD

**Issue by RedXander** [awslabs/aws-api-gateway-developer-portal#70]
Hi everyone.
I'm trying to learn and setup a developer portal but i have a big problem that i can't solve.
I want to customize Response Headers to shaw the "date" and "x-amzn-remapped-authorization" fields but i couldn't not find how to show them. 
![header problem](https://user-images.githubusercontent.com/39703721/40620633-d49847e2-6299-11e8-94d6-f30771f0bbfd.jpg)

As you can see only "pragma", "content-type" and "expires" fields are shawn and i don't know why. Anyone can help me??

**Comment by MynockSpit** [comment]
We recently launched a new version of the Dev Portal which uses a newer version of Swagger-UI. Could you give it a try and see if it's still the same behaviour?

**Comment by MynockSpit** [comment]
Hey -- going to resolve this. Please reopen if you try the new Dev Portal and are still having this issue!
