### ISSUE TITLE
How to validate a `HTTPS` Certificate and find if the caller is a valid caller

### ISSUE THREAD

**Issue by RameshRM** [awslabs/aws-api-gateway-developer-portal#71]
I Want to verify the `Security Certificate` and the Issuing Authority for the call I am receiving in `Api GateWay`. All I am expecting is only `Authorized` client can access the `Api Gateway` and the Call is not for the user, it is for trusted device. Is there a way to achieve this, can you help or share some docs 

Thx

**Comment by RameshRM** [comment]
@here , Can anyone look at it and help - Thx

**Comment by Trial-In-Error** [comment]
It sounds like you're probably looking for [Client Certificates](https://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started-client-side-ssl-authentication.html). Please re-open if this doesn't address your use case!
