### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by vdanniel** [awslabs/aws-api-gateway-developer-portal#74]
hi team, 

Post-configure.js set fails. 

{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1137:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  message: 'socket hang up',
  code: 'NetworkingError',
  path: null,
  host: 'cloudformation.ap-southeast-2.amazonaws.com',
  port: 443,
  localAddress: undefined,
  region: 'ap-southeast-2',
  hostname: 'cloudformation.ap-southeast-2.amazonaws.com',
  retryable: true,
  time: 2018-09-09T22:35:13.432Z }

checked the proxy and netstat is does seem to go through the proxy and not blocking it. 

Any advice. thanks

**Comment by Trial-In-Error** [comment]
Hmm. I haven't seen this before. There's a version 2 of the developer portal available on a branch named v2 that uses AWS SAM CLI to deploy; could you try that instead? It will likely provide better debugging output (especially if you run it with the debug flag, e.g., `aws sam --debug deploy ...`).

**Comment by Trial-In-Error** [comment]
Closing; v2 is now default, and these install scripts are no longer necessary.
