### ISSUE TITLE
IDs in plain text

### ISSUE THREAD

**Issue by phillyfan1138** [awslabs/aws-api-gateway-developer-portal#79]
When running the client side application, the "cognitoIdentityPoolId" and "cognitoClientId" are both viewable in plain text.  
1.  Is this safe?
2.  Is there any better practices for initiating the cognito client?  Googling showed varying opinions.  

Thanks!

**Comment by Trial-In-Error** [comment]
Hey!

If you look at this [AWS forum post](https://forums.aws.amazon.com/thread.jspa?threadID=245752&tstart=200), a member of the cognito team confirms that exposing the clientId and userPoolId should not be a concern, as they only calling unauth'd cognito endpoints with those. However, the token you receive back from STS should certainly be secured via HTTPS/SSL. There's a section in the project `README.md` titled "Before going to production" that has links to some documentation on setting up SSL for the S3 static website.
