### ISSUE TITLE
Site built using the procedure in the README doesn't work

### ISSUE THREAD

**Issue by jancona** [awslabs/aws-api-gateway-developer-portal#8]
When I run through the instructions in the README, the project build and deploys, but trying to use the portal fails immediately. In the JS console I get errors like: 
```
https://cognito-idp.your.amazonaws.com/ Failed to load resource: net::ERR_NAME_NOT_RESOLVED 
https://your_api_gateway_api_id.execute-api.your_primary_aws_region.amazonaws.com/prod/catalog?start=undefined&end=undefined Failed to load resource: net::ERR_NAME_NOT_RESOLVED
```

Basically it looks like a lot of the output from the CloudFormation stack failed to be substituted into the proper files. I can see config scripts that look like they should do that, but I don't know node.js at all and so have no idea what the problem is. I'm running on a Mac with node and they AWS CLI installed via Homebrew:

```
$ aws --version
aws-cli/1.11.29 Python/2.7.10 Darwin/15.6.0 botocore/1.4.86
$ node --version
v7.2.1
$ npm --version
3.10.9
```

**Comment by brettstack** [comment]
Sounds like that's the issue. Did you get any errors during the setup commands? Did your package.json get updated correctly (i.e. all "YOUR_*" have been replaced).

**Comment by jancona** [comment]
No, I still have the following:
```
    "apiGatewayApiId": "YOUR_API_GATEWAY_API_ID",
    "cognitoRegion": "YOUR_COGNITO_REGION",
    "cognitoUserPoolId": "YOUR_COGNITO_USER_POOL_ID",
    "cognitoClientId": "YOUR_COGNITO_CLIENT_ID",
    "cognitoIdentityPoolId": "YOUR_COGNITO_IDENTITY_POOL_ID",
```

**Comment by brettstack** [comment]
It looks like the post-config step didn't run, or errored. Try running `npm run post-config` manually. Alternatively, search your project for instances of "YOUR_" and replace with appropriate values.

**Comment by jancona** [comment]
When I run `npm run post-config` I get the following error:
```
$ npm run post-config

> aws-serverless-dev-portal-example@1.0.0 post-config /Users/jancona/projects/aws/aws-api-gateway-developer-portal
> node scripts/post-configure.js

{ AccessDenied: User: arn:aws:iam::4XXXXXXXXXXX:user/jancona is not authorized to perform: cloudformation:DescribeStacks on resource: arn:aws:cloudformation:us-east-1:4XXXXXXXXXXX:stack/jancona2-dev-portal-example/*
...
```
While I am user arn:aws:iam::4XXXXXXXXXXX:user/jancona, the account number in the stack ARN is incorrect. The account id in package.json is 1XXXXXXXXXXX. and my AWS_DEFAULT_PROFILE environment variable is set to a profile that includes a role in that account. Perhaps the post-configure.js script needs to assume that role before calling cloudformation:DescribeStacks?

**Comment by jancona** [comment]
I was able to get this to work one time by adding the following at line 10 of post-configure.js:
```
AWS.config.credentials = new AWS.TemporaryCredentials({
  RoleArn: 'arn:aws:iam::1XXXXXXXXXXX:role/YYYYYYYY',
  SerialNumber: 'arn:aws:iam::4XXXXXXXXXXX:mfa/jancona',
  TokenCode: 'ZZZZZZ'
});
```
To do this right, I would think that RoleArn and SerialNumber should come from  my `~/.aws/config` and the script should prompt for the MFA TokenCode.

**Comment by brettstack** [comment]
Glad to hear you got it working. I'll leave this open and mark as a bug.

**Comment by kramach** [comment]
I have run the deploy and have no errors in CF.
However when I try to signup or register I get this error.
https://cognito-idp.your.amazonaws.com/ net::ERR_NAME_NOT_RESOLVED

I did verify that the json files have been updated appropriately and there is no "YOUR" strings...
Which endpoint is this and how do I update it?
Thanks

**Comment by Trial-In-Error** [comment]
Hi! We have a new version of the developer portal on master that is deployed in an entirely different fashion. I'm closing this; if you have any issues with the new developer portal, please open a fresh issue. Thanks!
