### ISSUE TITLE
Remove version/timestamp from swaggerui layout

### ISSUE THREAD

**Issue by Trial-In-Error** [awslabs/aws-api-gateway-developer-portal#97]
Since API Gateway's exported version is just a timestamp, it doesn't really make sense to expose it as a 'version'. We should hide it. Maybe we could conditionally render it if the version isn't a timestamp? This would support showing the version of 'generic'/non-API Gateway managed swagger files.

**Comment by MynockSpit** [comment]
Closed by https://github.com/awslabs/aws-api-gateway-developer-portal/pull/174.

**Comment by mauritz72** [comment]
Actually, we would very much like to have the version back into the UI for API Gateway hosted APIs, since the version tag we provide during build for documentation-version is important for us to display to our external API users.
