### ISSUE TITLE
Update logo to not-squirrel

### ISSUE THREAD

**Issue by Trial-In-Error** [awslabs/aws-api-gateway-developer-portal#98]
Maybe use one of API Gateway's many logos? The pollen thing, perhaps?

**Comment by Trial-In-Error** [comment]
Closed by #113, once it gets merged. Sorry, :shipit:.

**Comment by MynockSpit** [comment]
Closed in [v2.1.0](https://github.com/awslabs/aws-api-gateway-developer-portal/releases/tag/v2.1.0).
